import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import esbuild from 'esbuild';
import { courseDataPath, courseDataSource } from './generate-course-data.mjs';

const normalizeNewlines = (value) => value.replace(/\r\n/g, '\n');
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8');
function resourceDataSource() {
  const questions = JSON.parse(read('_internal/quiz/questions.json')); const catalog = JSON.parse(read('_internal/references/catalog.json'));
  assert.ok(Array.isArray(questions) && questions.length, '_internal/quiz/questions.json must be a non-empty array.');
  assert.ok(Array.isArray(catalog) && catalog.length, '_internal/references/catalog.json must be a non-empty array.');
  const references = catalog.map((reference) => {
    assert.ok(reference && typeof reference.id === 'string' && typeof reference.title === 'string' && /^https:\/\//.test(reference.url || '') && ['primary', 'secondary'].includes(reference.kind) && typeof reference.summary === 'string', `Invalid reference catalog entry: ${reference?.id || 'unknown'}`);
    if (!reference.localPath) return { ...reference, sourceVersion: reference.sourceVersion || reference.version || '', content: '' };
    assert.ok(typeof reference.localPath === 'string' && !reference.localPath.startsWith('/') && !reference.localPath.split('/').includes('..'), `Unsafe localPath for ${reference.id}`);
    const raw = read(reference.localPath); const normalized = normalizeNewlines(raw); const hash = crypto.createHash('sha256').update(normalized).digest('hex');
    assert.ok(!reference.sha256 || reference.sha256 === hash, `Reference hash mismatch: ${reference.id}`);
    return { ...reference, sourceVersion: reference.sourceVersion || reference.version || '', content: normalized };
  });
  const cheatSheet = { title: 'GitHub Actions cheat sheet', content: normalizeNewlines(read('_internal/docs/CHEAT_SHEET.md')) };
  const coverage = { title: 'GH-200 blueprint coverage', content: normalizeNewlines(read('_internal/docs/BLUEPRINT.md')) };
  return `// Generated by _internal/scripts/build-course.mjs; do not hand-edit.\nexport const questions = ${JSON.stringify(questions, null, 2)};\nexport const references = ${JSON.stringify(references, null, 2)};\nexport const cheatSheet = ${JSON.stringify(cheatSheet, null, 2)};\nexport const coverage = ${JSON.stringify(coverage, null, 2)};\n`;
}
assert.equal(normalizeNewlines(fs.readFileSync(courseDataPath, 'utf8')), normalizeNewlines(courseDataSource()), '_internal/learning/course-data.mjs is stale; run npm run build:course');
assert.equal(normalizeNewlines(read('_internal/visual-source/course-resources.mjs')), normalizeNewlines(resourceDataSource()), '_internal/visual-source/course-resources.mjs is stale; run npm run build:course');
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'gh200-course-'));
try {
  const output = path.join(directory, 'course-runtime.js');
  await esbuild.build({ absWorkingDir: root, entryPoints: ['_internal/visual-source/runtime-entry.mjs'], bundle: true, format: 'iife', platform: 'browser', target: ['es2018'], outfile: output, legalComments: 'none', minifyWhitespace: true });
  assert.equal(normalizeNewlines(fs.readFileSync(path.join(root, 'visual/web/course-runtime.js'), 'utf8')), normalizeNewlines(fs.readFileSync(output, 'utf8')), 'visual/web/course-runtime.js is stale; run npm run build:course');
  console.log('Course bundle matches source data and runtime entry.');
} finally { fs.rmSync(directory, { recursive: true, force: true }); }
