name: output
on: {workflow_dispatch: {}}
jobs: {prepare: {runs-on: ubuntu-latest, outputs: {version: '${{ steps.version.outputs.version }}'}, steps: [{id: version, run: 'echo version=1 >> "$GITHUB_OUTPUT"'}]}}
