import esbuild from 'esbuild';
import crypto from 'node:crypto';
import fs from 'node:fs';
import { writeCourseData } from './generate-course-data.mjs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const normalize = (value) => value.replace(/\r\n/g, '\n');
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8');
function resourceDataSource() {
  const questions = JSON.parse(read('quiz/questions.json'));
  const catalog = JSON.parse(read('references/catalog.json'));
  if (!Array.isArray(questions) || !questions.length) throw new Error('quiz/questions.json must be a non-empty array.');
  if (!Array.isArray(catalog) || !catalog.length) throw new Error('references/catalog.json must be a non-empty array.');
  const references = catalog.map((reference) => {
    if (!reference || typeof reference.id !== 'string' || typeof reference.title !== 'string' || !/^https:\/\//.test(reference.url || '') || !['primary', 'secondary'].includes(reference.kind) || typeof reference.summary !== 'string') throw new Error(`Invalid reference catalog entry: ${reference?.id || 'unknown'}`);
    if (!reference.localPath) return { ...reference, sourceVersion: reference.sourceVersion || reference.version || '', content: '' };
    if (typeof reference.localPath !== 'string' || reference.localPath.startsWith('/') || reference.localPath.split('/').includes('..')) throw new Error(`Unsafe localPath for ${reference.id}`);
    const raw = read(reference.localPath); const normalized = normalize(raw); const hash = crypto.createHash('sha256').update(normalized).digest('hex');
    if (reference.sha256 && reference.sha256 !== hash) throw new Error(`Reference hash mismatch: ${reference.id}`);
    return { ...reference, sourceVersion: reference.sourceVersion || reference.version || '', content: normalized };
  });
  const cheatSheet = { title: 'GitHub Actions cheat sheet', content: normalize(read('docs/CHEAT_SHEET.md')) };
  const coverage = { title: 'GH-200 blueprint coverage', content: normalize(read('docs/BLUEPRINT.md')) };
  return `// Generated by scripts/build-course.mjs; do not hand-edit.\nexport const questions = ${JSON.stringify(questions, null, 2)};\nexport const references = ${JSON.stringify(references, null, 2)};\nexport const cheatSheet = ${JSON.stringify(cheatSheet, null, 2)};\nexport const coverage = ${JSON.stringify(coverage, null, 2)};\n`;
}
writeCourseData();
fs.writeFileSync(path.join(root, 'web/course-resources.mjs'), resourceDataSource());
await esbuild.build({ absWorkingDir: root, entryPoints: ['web/runtime-entry.mjs'], bundle: true, format: 'iife', platform: 'browser', target: ['es2018'], outfile: 'web/course-runtime.js', legalComments: 'none', minifyWhitespace: true });
