// Human-first course copy for the browser. Keep YAML tasks and validation in the manifest/fixtures.
export const courseCopy = {
  '01-first-workflow': ['Make a workflow you can start yourself', 'Tell GitHub exactly when this small automation recipe may run.', ['A workflow is a recipe GitHub follows. An event is the bell that tells GitHub to start reading that recipe; a job is one group of work, and a step is one command inside it.', 'Here you will add a manual event. It gives a person a Run workflow button, which is useful for a check that should only happen when somebody asks for it.', 'Keep the existing build job: its runner chooses the computer, and its step is the command that computer will perform.']],
  '02-job-and-runner': ['Choose the computer that runs your job', 'Tell GitHub to run these commands on an Ubuntu machine.', ['A job needs a computer before it can do any work. GitHub calls that computer a runner.', 'GitHub can provide a fresh Ubuntu runner for common tasks. You will name that runner for the build job.', 'The runs-on setting belongs inside the job; the steps underneath are the commands that runner will perform.']],
  '03-push-filter': ['Run only for the changes that matter', 'Limit this workflow to main-branch changes under src/.', ['A push event can happen for many branches and many files. Filters let a workflow ignore changes that do not need this particular check.', 'You will keep this workflow focused on the main branch and source-code files. That avoids spending time on unrelated edits.', 'Put both filters below the push event: branch filters choose a branch, while path filters choose files.']],
  '04-context-as-data': ['Handle event information safely', 'Put event text in an environment variable before using it in a command.', ['GitHub provides context values such as the text from an event. Treat that text like input from outside your script: it may contain spaces or special shell characters.', 'An environment variable is a named value a command can read. You will pass the event text through one and quote it before printing it.', 'Quoting "$EVENT_TEXT" keeps the shell from splitting one message into unexpected pieces.']],
  '05-job-output': ['Pass one result from a job', 'Share the version from prepare with another job.', ['Jobs are separate pieces of work. A value made in one job does not automatically appear in the next one.', 'An output is a named result a job deliberately shares. You will connect a step output to a job output named version.', 'Think of it as a two-part label: the step writes version first, then the job exposes that named value.']],
  '06-needs-output': ['Use a result from an earlier job', 'Make report wait for prepare and print its version.', ['A later job must say which earlier job it depends on. GitHub calls that relationship needs.', 'Once the dependency exists, the later job can read a named output from the earlier one. You will write both parts of that handoff.', 'Write `needs: prepare` to set the order, then use the prepare output where report prints its message.']],
  '07-matrix': ['Repeat a job for more than one version', 'Repeat this job for the values 20 and 22.', ['A matrix is a list that tells GitHub to repeat the same job with different values. It is a simple way to cover more than one supported version.', 'You will add two Node values. GitHub would create one job variation for each value in a real run.', 'A matrix supplies values; it does not install Node by itself. A later step would use each value to choose an installed version.']],
  '08-service-linux': ['Give a job a temporary Redis helper', 'Run the test job on Ubuntu with a healthy Redis service.', ['Some tests need a helper program such as Redis. A service is a temporary helper container that lives alongside one job.', 'You will use an Ubuntu runner and add a health check so the job waits for Redis to be ready.', 'The health command answers one important question before tests begin: is the helper ready to accept work?']],
  '09-reusable-call': ['Call a shared workflow', 'Use the organization’s reusable risk workflow and keep its input.', ['A reusable workflow is a complete workflow another workflow can call. It is different from an ordinary job with its own runner and steps.', 'You will point the risk job at the shared workflow and keep the sample-size setting it needs.', 'The called workflow owns its own runner and steps, so this job only names what to call and the value to pass in.']],
  '10-composite-action': ['Describe a small reusable action', 'Declare a composite action with one safe shell step.', ['An action is reusable automation. A composite action is the simplest kind: it groups normal workflow steps behind one name.', 'You will say that this action uses the composite model and give its command an explicit shell.', 'Naming bash makes the command’s language clear, which helps the action behave consistently for every caller.']],
  '11-failure-evidence': ['Keep useful notes when a job fails', 'Write diagnostic evidence even after an earlier test step fails.', ['When a job fails, the most useful details can disappear unless you save them. A job summary is a note shown with a GitHub Actions run.', 'You will use always() so the evidence step still runs, then write its note to the summary file.', 'That note gives the next person a quick place to start instead of making them search every log line.']],
  '12-runner-policy': ['Use only approved self-hosted computers', 'Label the scan job with self-hosted and approved.', ['Some organizations run their own computers instead of GitHub-hosted runners. Labels are short names GitHub uses to choose a matching computer.', 'You will require both the self-hosted label and the organization’s approved label.', 'Using both labels narrows the match. Runner groups and repository access decide whether the job is actually permitted to use that computer.']],
  '13-least-privilege': ['Give the workflow only the access it needs', 'Set repository permissions to read contents only.', ['A token is a temporary credential GitHub gives a workflow. Permissions are the keys that say what that token may do.', 'Safer workflows start with the smallest useful key. You will allow reading repository contents and nothing more.', 'If a later job truly needs more access, make that choice visible and limited to that job instead of widening everything.']],
  '14-oidc-job': ['Keep cloud login permission in one job', 'Give only deploy the permission and environment it needs.', ['OIDC is a way for a job to ask a cloud provider for a short-lived identity instead of storing a long-lived secret. It is powerful, so it should stay in the one job that needs it.', 'An environment is a named deployment target such as production. You will keep normal read access at the workflow level and put the special cloud permission on deploy.', 'Production rules and cloud trust are configured outside this file; this workflow declares the narrow job that may request that identity.']],
  '15-sha-pin': ['Use an exact action version you can review', 'Replace the moving checkout tag with the verified full commit SHA.', ['An action reference can point to a moving tag such as v4, or to one exact commit. A SHA is the long unique identifier for that exact commit.', 'Using the full verified SHA makes later reviews reproducible: everyone can see exactly what code the workflow chose.', 'You will copy the approved SHA already noted in the starter file, not invent a new one.']],
  '16-upload-artifact': ['Save a build result for later', 'Upload the dist folder as a named build artifact.', ['An artifact is a file or folder saved after a workflow run. It is useful for build output, logs, or files another job needs to inspect.', 'You will give the saved output a clear name and point it at the dist folder.', 'A clear artifact name makes it easier to find the right build result when several jobs or runs exist.']],
  '17-capstone-gate': ['Stop deployment until the build succeeds', 'Make deploy wait for build while keeping read-only access.', ['A deployment should not start before its required build is finished. A dependency is the explicit link that makes one job wait for another.', 'You will add that gate and keep the deployment job’s permissions small. This combines ordering and access control from earlier lessons.', 'This is the pattern to carry forward: say what must finish first, then give the next job only the access it needs.']]
};

export const courseInstructions = {
  '01-first-workflow': ['Find the top-level `on: false` line.', 'Replace it with `on:` and add the indented line `workflow_dispatch: {}` beneath it.', 'Keep the existing `jobs.build` job and its step unchanged.'],
  '02-job-and-runner': ['Find the `jobs.build` mapping.', 'Add `runs-on: ubuntu-latest` inside build, aligned with `steps`.', 'Keep the existing build step.'],
  '03-push-filter': ['Find the top-level `on.push` event.', 'Add `branches: [main]` and `paths: [src/**]` inside that push mapping.', 'Keep both filters under push, not beside it.'],
  '04-context-as-data': ['Find the `inspect` step that prints event text directly.', 'Add `env.EVENT_TEXT` with the GitHub event expression.', 'Change the command to print quoted `$EVENT_TEXT` and remove direct event interpolation from `run`.'],
  '05-job-output': ['Find the `prepare` job and its version step.', 'Give that step the id `version` and write its value to `$GITHUB_OUTPUT`.', 'Add `prepare.outputs.version` that points at `steps.version.outputs.version`.'],
  '06-needs-output': ['Find the `prepare` job and give its producing step id `v`.', 'Expose `prepare.outputs.version` from `steps.v.outputs.version`.', 'In `report`, add `needs: prepare` and print `needs.prepare.outputs.version`.'],
  '07-matrix': ['Find the `test` job.', 'Add `strategy.matrix.node` under that job.', 'Put both values, 20 and 22, in the node list.'],
  '08-service-linux': ['Find the `test` job and set `runs-on: ubuntu-latest`.', 'Add a `services.redis` mapping with image `redis:7`.', 'Add Redis options containing a `health-cmd` readiness check.'],
  '09-reusable-call': ['Find the `risk` job.', 'Remove its `runs-on` and `steps` fields.', 'Add `uses: ./.github/workflows/reusable-risk.yml` and keep `with.sample_size: 3`.'],
  '10-composite-action': ['Find the top-level `runs` mapping.', 'Set `runs.using: composite`.', 'Add one item in `runs.steps` with `shell: bash` and a command containing `echo hello`.'],
  '11-failure-evidence': ['Find the evidence-writing step in the `test` job.', 'Set its `if` value to `always()` so it still runs after failure.', 'Write its message to `$GITHUB_STEP_SUMMARY`.'],
  '12-runner-policy': ['Find the `scan` job runner setting.', 'Replace it with the list `[self-hosted, approved]`.', 'Do not add other runner labels.'],
  '13-least-privilege': ['Find the top-level `permissions` mapping.', 'Set it to exactly `contents: read`.', 'Remove any broader job-level permissions or make them exactly the same read-only mapping.'],
  '14-oidc-job': ['Set top-level permissions to `contents: read`.', 'On `deploy`, add `environment: production`.', 'Set only deploy job permissions to `id-token: write` and `contents: read`.'],
  '15-sha-pin': ['Find the checkout step in the `build` job.', 'Replace `actions/checkout@v4` with the full approved SHA in the starter comment.', 'Keep the action name and do not add text after the 40-character SHA.'],
  '16-upload-artifact': ['Find the `build` job steps.', 'Add an `actions/upload-artifact@v4` step.', 'Set its `with.name` to `build-output` and `with.path` to `dist`.'],
  '17-capstone-gate': ['Find the `deploy` job.', 'Add `needs: build` so deployment waits for the build job.', 'Keep deploy permissions read-only; do not add any write permission.']
};

export const courseOutcomes = {
  '01-first-workflow': 'The YAML has a workflow_dispatch mapping and still has a valid build job.',
  '02-job-and-runner': 'The build job names ubuntu-latest as its runner.',
  '03-push-filter': 'Push is limited to main and src/** changes.',
  '04-context-as-data': 'Event text crosses an environment-variable boundary and is quoted in the command.',
  '05-job-output': 'Prepare exposes version from its named step output.',
  '06-needs-output': 'Report depends on prepare and reads its version output.',
  '07-matrix': 'The matrix contains both 20 and 22.',
  '08-service-linux': 'The Ubuntu test job includes Redis with a health command.',
  '09-reusable-call': 'Risk calls the approved reusable workflow with sample size 3.',
  '10-composite-action': 'The action declares composite runs and a bash echo step.',
  '11-failure-evidence': 'The evidence step uses always() and writes to the job summary.',
  '12-runner-policy': 'Scan has exactly self-hosted and approved runner labels.',
  '13-least-privilege': 'All declared permissions are exactly contents: read.',
  '14-oidc-job': 'Only deploy has OIDC permission and it targets production.',
  '15-sha-pin': 'Checkout uses the one approved full SHA.',
  '16-upload-artifact': 'Build uploads dist as build-output.',
  '17-capstone-gate': 'Deploy waits for build and has no write permission.'
};
