// Generated by scripts/build-course.mjs; do not hand-edit.
export const lessons = [
  {
    "id": "01-first-workflow",
    "index": 1,
    "title": "Make a workflow you can start yourself",
    "stage": "Foundations",
    "summary": "Tell GitHub exactly when this small automation recipe may run.",
    "explanation": [
      "A workflow is a recipe GitHub follows. An event is the bell that tells GitHub to start reading that recipe; a job is one group of work, and a step is one command inside it.",
      "Here you will add a manual event. It gives a person a Run workflow button, which is useful for a check that should only happen when somebody asks for it.",
      "Keep the existing build job: its runner chooses the computer, and its step is the command that computer will perform."
    ],
    "instructions": [
      "Find `on: false` near the top of the file.",
      "Replace it with `on:`, then put `workflow_dispatch: {}` on the next line with two spaces before it.",
      "Leave the `build` job and its command as they are."
    ],
    "doneWhen": "GitHub shows a Run workflow button, and the build job is still present.",
    "task": "Make this workflow run only when someone clicks Run workflow on GitHub.",
    "editLocation": "Near the top of `workflow.yml`, replace the `on: false` line.",
    "keep": "Keep the whole `build` job and its command unchanged.",
    "editExample": "on:\n  workflow_dispatch: {}",
    "example": "name: greeting\n\non:\n  workflow_dispatch: {}\n\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "starter": "name: first\non: false\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "solution": "name: first\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "file": "workflow.yml",
    "hint": "Near the top of `workflow.yml`, replace the `on: false` line.",
    "success": "GitHub shows a Run workflow button, and the build job is still present.",
    "source": {
      "label": "GitHub’s event documentation",
      "url": "https://docs.github.com/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow"
    },
    "rules": [
      "workflow_dispatch"
    ]
  },
  {
    "id": "02-job-and-runner",
    "index": 2,
    "title": "Choose the computer that runs your job",
    "stage": "Foundations",
    "summary": "Tell GitHub to run these commands on an Ubuntu machine.",
    "explanation": [
      "A job needs a computer before it can do any work. GitHub calls that computer a runner.",
      "GitHub can provide a fresh Ubuntu runner for common tasks. You will name that runner for the build job.",
      "The runs-on setting belongs inside the job; the steps underneath are the commands that runner will perform."
    ],
    "instructions": [
      "Find the `build` job under `jobs:`.",
      "Inside `build`, add `runs-on: ubuntu-latest` on a new line lined up with `steps:`.",
      "Leave the existing command in `steps:` unchanged."
    ],
    "doneWhen": "The build job is set to use an Ubuntu computer.",
    "task": "Choose the Ubuntu computer that runs the build job.",
    "editLocation": "Inside the `build` job, on a new line lined up with `steps:`.",
    "keep": "Keep the existing build step unchanged.",
    "editExample": "runs-on: ubuntu-latest",
    "example": "",
    "starter": "name: runner\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    steps:\n      - run: echo build\n",
    "solution": "name: runner\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo build\n",
    "file": "workflow.yml",
    "hint": "Inside the `build` job, on a new line lined up with `steps:`.",
    "success": "The build job is set to use an Ubuntu computer.",
    "source": {
      "label": "Choose runners",
      "url": "https://docs.github.com/actions/how-tos/write-workflows/choose-where-workflows-run/choose-the-runner-for-a-job"
    },
    "rules": [
      "build-ubuntu"
    ]
  },
  {
    "id": "03-push-filter",
    "index": 3,
    "title": "Run only for the changes that matter",
    "stage": "Foundations",
    "summary": "Limit this workflow to main-branch changes under src/.",
    "explanation": [
      "A push event can happen for many branches and many files. Filters let a workflow ignore changes that do not need this particular check.",
      "You will keep this workflow focused on the main branch and source-code files. That avoids spending time on unrelated edits.",
      "Put both filters below the push event: branch filters choose a branch, while path filters choose files."
    ],
    "instructions": [
      "Find `push:` under `on:`.",
      "Inside `push`, add `paths: [src/**]` on a new line lined up with `branches:`.",
      "Leave `branches: [main]` and the `build` job unchanged."
    ],
    "doneWhen": "The workflow responds only to changes in `src/` on `main`.",
    "task": "Run this workflow only when files in `src/` change on `main`.",
    "editLocation": "Inside `push:`, on a new line lined up with `branches:`.",
    "keep": "Keep the existing `branches: [main]` filter and the build job.",
    "editExample": "paths: [src/**]",
    "example": "",
    "starter": "name: filter\non:\n  push:\n    branches:\n      - main\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "solution": "name: filter\non:\n  push:\n    branches:\n      - main\n    paths:\n      - 'src/**'\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "file": "workflow.yml",
    "hint": "Inside `push:`, on a new line lined up with `branches:`.",
    "success": "The workflow responds only to changes in `src/` on `main`.",
    "source": {
      "label": "Workflow filters",
      "url": "https://docs.github.com/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore"
    },
    "rules": [
      "push-filter"
    ]
  },
  {
    "id": "04-context-as-data",
    "index": 4,
    "title": "Handle event information safely",
    "stage": "Foundations",
    "summary": "Put event text in an environment variable before using it in a command.",
    "explanation": [
      "GitHub provides context values such as the text from an event. Treat that text like input from outside your script: it may contain spaces or special shell characters.",
      "An environment variable is a named value a command can read. You will pass the event text through one and quote it before printing it.",
      "Quoting \"$EVENT_TEXT\" keeps the shell from splitting one message into unexpected pieces."
    ],
    "instructions": [
      "Find the command in the `inspect` job that contains `${{ github.event.issue.title }}`.",
      "In that same step, add `env:` and place `EVENT_TEXT: ${{ github.event.issue.title }}` below it with two more spaces.",
      "Change the command to `printf \"%s\\n\" \"$EVENT_TEXT\"`; do not leave the GitHub value in the command."
    ],
    "doneWhen": "The issue title is saved as `EVENT_TEXT` before the command prints it.",
    "task": "Put the issue title in a named value before printing it safely.",
    "editLocation": "Inside the existing step in the `inspect` job, beside its `run:` line.",
    "keep": "Keep the `inspect` job and its runner.",
    "editExample": "env:\n  EVENT_TEXT: ${{ github.event.issue.title }}",
    "example": "",
    "starter": "name: context\non:\n  workflow_dispatch:\n    {}\njobs:\n  inspect:\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'echo ${{ github.event.issue.title }}'\n",
    "solution": "name: context\non:\n  workflow_dispatch:\n    {}\njobs:\n  inspect:\n    runs-on: ubuntu-latest\n    steps:\n      - env:\n          EVENT_TEXT: '${{ github.event.issue.title }}'\n        run: 'printf \"%s\\\\n\" \"$EVENT_TEXT\"'\n",
    "file": "workflow.yml",
    "hint": "Inside the existing step in the `inspect` job, beside its `run:` line.",
    "success": "The issue title is saved as `EVENT_TEXT` before the command prints it.",
    "source": {
      "label": "Contexts",
      "url": "https://docs.github.com/actions/learn-github-actions/contexts"
    },
    "rules": [
      "safe-env"
    ]
  },
  {
    "id": "05-job-output",
    "index": 5,
    "title": "Pass one result from a job",
    "stage": "Connect jobs",
    "summary": "Share the version from prepare with another job.",
    "explanation": [
      "Jobs are separate pieces of work. A value made in one job does not automatically appear in the next one.",
      "An output is a named result a job deliberately shares. You will connect a step output to a job output named version.",
      "Think of it as a two-part label: the step writes version first, then the job exposes that named value."
    ],
    "instructions": [
      "Find the `prepare` job and the step with `id: version`.",
      "Inside `prepare`, add `outputs:` with `version: ${{ steps.version.outputs.version }}` below it.",
      "Leave the step id `version` and its line that writes to `$GITHUB_OUTPUT` unchanged."
    ],
    "doneWhen": "The `prepare` job makes its version available under the name `version`.",
    "task": "Make the version created by `prepare` available to another job.",
    "editLocation": "Inside the `prepare` job, on a new line lined up with `runs-on:` and `steps:`.",
    "keep": "Keep the existing `version` step and its `$GITHUB_OUTPUT` line.",
    "editExample": "outputs:\n  version: ${{ steps.version.outputs.version }}",
    "example": "",
    "starter": "name: output\non:\n  workflow_dispatch:\n    {}\njobs:\n  prepare:\n    runs-on: ubuntu-latest\n    steps:\n      - id: version\n        run: 'echo version=1 >> \"$GITHUB_OUTPUT\"'\n",
    "solution": "name: output\non:\n  workflow_dispatch:\n    {}\njobs:\n  prepare:\n    runs-on: ubuntu-latest\n    outputs:\n      version: '${{ steps.version.outputs.version }}'\n    steps:\n      - id: version\n        run: 'echo version=1 >> \"$GITHUB_OUTPUT\"'\n",
    "file": "workflow.yml",
    "hint": "Inside the `prepare` job, on a new line lined up with `runs-on:` and `steps:`.",
    "success": "The `prepare` job makes its version available under the name `version`.",
    "source": {
      "label": "Passing job outputs",
      "url": "https://docs.github.com/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs"
    },
    "rules": [
      "job-output"
    ]
  },
  {
    "id": "06-needs-output",
    "index": 6,
    "title": "Use a result from an earlier job",
    "stage": "Connect jobs",
    "summary": "Make report wait for prepare and print its version.",
    "explanation": [
      "A later job must say which earlier job it depends on. GitHub calls that relationship needs.",
      "Once the dependency exists, the later job can read a named output from the earlier one. You will write both parts of that handoff.",
      "Write `needs: prepare` to set the order, then use the prepare output where report prints its message."
    ],
    "instructions": [
      "Find the `report` job.",
      "Inside `report`, add `needs: prepare` on a new line lined up with `runs-on:`.",
      "Change its command so it prints `${{ needs.prepare.outputs.version }}`. Leave the `prepare` job unchanged."
    ],
    "doneWhen": "The report job waits for prepare and prints the version it made.",
    "task": "Make `report` wait for `prepare` and print its version.",
    "editLocation": "Inside the `report` job, on new lines lined up with `runs-on:`.",
    "keep": "Keep the complete `prepare` job unchanged.",
    "editExample": "needs: prepare",
    "example": "",
    "starter": "name: needs\non:\n  workflow_dispatch:\n    {}\njobs:\n  prepare:\n    runs-on: ubuntu-latest\n    outputs:\n      version: '${{ steps.v.outputs.version }}'\n    steps:\n      - id: v\n        run: 'echo version=1 >> \"$GITHUB_OUTPUT\"'\n  report:\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'echo missing'\n",
    "solution": "name: needs\non:\n  workflow_dispatch:\n    {}\njobs:\n  prepare:\n    runs-on: ubuntu-latest\n    outputs:\n      version: '${{ steps.v.outputs.version }}'\n    steps:\n      - id: v\n        run: 'echo version=1 >> \"$GITHUB_OUTPUT\"'\n  report:\n    needs: prepare\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'echo ${{ needs.prepare.outputs.version }}'\n",
    "file": "workflow.yml",
    "hint": "Inside the `report` job, on new lines lined up with `runs-on:`.",
    "success": "The report job waits for prepare and prints the version it made.",
    "source": {
      "label": "Job dependencies and outputs",
      "url": "https://docs.github.com/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs"
    },
    "rules": [
      "needs-output"
    ]
  },
  {
    "id": "07-matrix",
    "index": 7,
    "title": "Repeat a job for more than one version",
    "stage": "Connect jobs",
    "summary": "Repeat this job for the values 20 and 22.",
    "explanation": [
      "A matrix is a list that tells GitHub to repeat the same job with different values. It is a simple way to cover more than one supported version.",
      "You will add two Node values. GitHub would create one job variation for each value in a real run.",
      "A matrix supplies values; it does not install Node by itself. A later step would use each value to choose an installed version."
    ],
    "instructions": [
      "Find the `node` list inside the `test` job.",
      "Add `22` after `20`, so the list is `[20, 22]`.",
      "Leave the runner and test command unchanged."
    ],
    "doneWhen": "The test job is set to run with both 20 and 22.",
    "task": "Create two versions of the test job, one labeled Node 20 and one labeled Node 22.",
    "editLocation": "Inside the existing `node` list in the `test` job.",
    "keep": "Keep the runner and the test command unchanged.",
    "editExample": "node: [20, 22]",
    "example": "",
    "starter": "name: matrix\non:\n  workflow_dispatch:\n    {}\njobs:\n  test:\n    runs-on: ubuntu-latest\n    strategy:\n      matrix:\n        node:\n          - 20\n    steps:\n      - run: echo test\n",
    "solution": "name: matrix\non:\n  workflow_dispatch:\n    {}\njobs:\n  test:\n    runs-on: ubuntu-latest\n    strategy:\n      matrix:\n        node:\n          - 20\n          - 22\n    steps:\n      - run: echo test\n",
    "file": "workflow.yml",
    "hint": "Inside the existing `node` list in the `test` job.",
    "success": "The test job is set to run with both 20 and 22.",
    "source": {
      "label": "Matrix strategy",
      "url": "https://docs.github.com/actions/using-jobs/using-a-matrix-for-your-jobs"
    },
    "rules": [
      "node-matrix"
    ]
  },
  {
    "id": "08-service-linux",
    "index": 8,
    "title": "Give a job a temporary Redis helper",
    "stage": "Connect jobs",
    "summary": "Run the test job on Ubuntu with a healthy Redis service.",
    "explanation": [
      "Some tests need a helper program such as Redis. A service is a temporary helper container that lives alongside one job.",
      "You will use an Ubuntu runner and add a health check so the job waits for Redis to be ready.",
      "The health command answers one important question before tests begin: is the helper ready to accept work?"
    ],
    "instructions": [
      "Find `services:` inside the `test` job.",
      "Inside `redis`, add `options: --health-cmd \"redis-cli ping\"` on a new line lined up with `image:`.",
      "Leave `runs-on: ubuntu-latest`, the Redis image, and the test command unchanged."
    ],
    "doneWhen": "The test job has Redis and checks that Redis is ready.",
    "task": "Make the test job wait until its Redis helper is ready.",
    "editLocation": "Inside `redis:` under `services:` in the `test` job, on a new line lined up with `image:`.",
    "keep": "Keep the Ubuntu runner, Redis image, and test command unchanged.",
    "editExample": "options: --health-cmd \"redis-cli ping\"",
    "example": "",
    "starter": "name: service\non:\n  workflow_dispatch:\n    {}\njobs:\n  test:\n    runs-on: ubuntu-latest\n    services:\n      redis:\n        image: redis:7\n    steps:\n      - run: echo test\n",
    "solution": "name: service\non:\n  workflow_dispatch:\n    {}\njobs:\n  test:\n    runs-on: ubuntu-latest\n    services:\n      redis:\n        image: redis:7\n        options: '--health-cmd \"redis-cli ping\"'\n    steps:\n      - run: echo test\n",
    "file": "workflow.yml",
    "hint": "Inside `redis:` under `services:` in the `test` job, on a new line lined up with `image:`.",
    "success": "The test job has Redis and checks that Redis is ready.",
    "source": {
      "label": "Service containers",
      "url": "https://docs.github.com/actions/using-containerized-services/about-service-containers"
    },
    "rules": [
      "healthy-redis"
    ]
  },
  {
    "id": "09-reusable-call",
    "index": 9,
    "title": "Call a shared workflow",
    "stage": "Reuse and debug",
    "summary": "Use the organization’s reusable risk workflow and keep its input.",
    "explanation": [
      "A reusable workflow is a complete workflow another workflow can call. It is different from an ordinary job with its own runner and steps.",
      "You will point the risk job at the shared workflow and keep the sample-size setting it needs.",
      "The called workflow owns its own runner and steps, so this job only names what to call and the value to pass in."
    ],
    "instructions": [
      "Find the `risk` job.",
      "Replace its `runs-on:` and `steps:` lines with `uses: ./.github/workflows/reusable-risk.yml`.",
      "Leave `with:` and `sample_size: 3` in the `risk` job."
    ],
    "doneWhen": "The risk job uses the shared workflow and keeps the sample size of 3.",
    "task": "Use the shared risk workflow for the `risk` job.",
    "editLocation": "Inside the `risk` job, where `runs-on:` and `steps:` are now.",
    "keep": "Keep `with:` and `sample_size: 3` unchanged.",
    "editExample": "uses: ./.github/workflows/reusable-risk.yml",
    "example": "",
    "starter": "name: reuse\non:\n  workflow_dispatch:\n    {}\njobs:\n  risk:\n    with:\n      sample_size: 3\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo replace\n",
    "solution": "name: reuse\non:\n  workflow_dispatch:\n    {}\njobs:\n  risk:\n    uses: './.github/workflows/reusable-risk.yml'\n    with:\n      sample_size: 3\n",
    "file": "workflow.yml",
    "hint": "Inside the `risk` job, where `runs-on:` and `steps:` are now.",
    "success": "The risk job uses the shared workflow and keeps the sample size of 3.",
    "source": {
      "label": "Reusing workflows",
      "url": "https://docs.github.com/actions/sharing-automations/reusing-workflows"
    },
    "rules": [
      "reusable-call"
    ]
  },
  {
    "id": "10-composite-action",
    "index": 10,
    "title": "Describe a small reusable action",
    "stage": "Reuse and debug",
    "summary": "Declare a composite action with one safe shell step.",
    "explanation": [
      "An action is reusable automation. A composite action is the simplest kind: it groups normal workflow steps behind one name.",
      "You will say that this action uses the composite model and give its command an explicit shell.",
      "Naming bash makes the command’s language clear, which helps the action behave consistently for every caller."
    ],
    "instructions": [
      "Find `runs:` in `action.yml`.",
      "Change `using: node20` to `using: composite`, then add `steps:` below it.",
      "Under `steps:`, add one step with `run: echo hello` and `shell: bash`."
    ],
    "doneWhen": "The action is set up as a composite action with a Bash hello command.",
    "task": "Turn this action into a reusable action that says hello.",
    "editLocation": "Under the top-level `runs:` section in `action.yml`.",
    "keep": "Keep the action name `hello` unchanged.",
    "editExample": "runs:\n  using: composite\n  steps:\n    - run: echo hello\n      shell: bash",
    "example": "",
    "starter": "name: hello\nruns:\n  using: node20\n",
    "solution": "name: hello\nruns:\n  using: composite\n  steps:\n    - run: 'echo hello'\n      shell: bash\n",
    "file": "action.yml",
    "hint": "Under the top-level `runs:` section in `action.yml`.",
    "success": "The action is set up as a composite action with a Bash hello command.",
    "source": {
      "label": "Composite actions",
      "url": "https://docs.github.com/actions/sharing-automations/creating-actions/creating-a-composite-action"
    },
    "rules": [
      "composite"
    ]
  },
  {
    "id": "11-failure-evidence",
    "index": 11,
    "title": "Keep useful notes when a job fails",
    "stage": "Reuse and debug",
    "summary": "Write diagnostic evidence even after an earlier test step fails.",
    "explanation": [
      "When a job fails, the most useful details can disappear unless you save them. A job summary is a note shown with a GitHub Actions run.",
      "You will use always() so the evidence step still runs, then write its note to the summary file.",
      "That note gives the next person a quick place to start instead of making them search every log line."
    ],
    "instructions": [
      "Find the `steps:` list in the `test` job.",
      "Add a new step after the failing command with `if: ${{ always() }}` and a command that appends `evidence` to `$GITHUB_STEP_SUMMARY`.",
      "Leave the existing `exit 1` command unchanged."
    ],
    "doneWhen": "The new note step runs even after a failure and saves a note in the run summary.",
    "task": "Save a short note even when the earlier test command fails.",
    "editLocation": "Inside the `steps:` list in the `test` job, after the `exit 1` step.",
    "keep": "Keep the existing failing command unchanged.",
    "editExample": "- if: ${{ always() }}\n  run: echo evidence >> \"$GITHUB_STEP_SUMMARY\"",
    "example": "",
    "starter": "name: evidence\non:\n  workflow_dispatch:\n    {}\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'exit 1'\n",
    "solution": "name: evidence\non:\n  workflow_dispatch:\n    {}\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'exit 1'\n      - if: '${{ always() }}'\n        name: evidence\n        run: 'echo evidence >> \"$GITHUB_STEP_SUMMARY\"'\n",
    "file": "workflow.yml",
    "hint": "Inside the `steps:` list in the `test` job, after the `exit 1` step.",
    "success": "The new note step runs even after a failure and saves a note in the run summary.",
    "source": {
      "label": "Status check functions",
      "url": "https://docs.github.com/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions"
    },
    "rules": [
      "failure-evidence"
    ]
  },
  {
    "id": "12-runner-policy",
    "index": 12,
    "title": "Use only approved self-hosted computers",
    "stage": "Secure delivery",
    "summary": "Label the scan job with self-hosted and approved.",
    "explanation": [
      "Some organizations run their own computers instead of GitHub-hosted runners. Labels are short names GitHub uses to choose a matching computer.",
      "You will require both the self-hosted label and the organization’s approved label.",
      "Using both labels narrows the match. Runner groups and repository access decide whether the job is actually permitted to use that computer."
    ],
    "instructions": [
      "Find `runs-on:` in the `scan` job.",
      "Replace `unapproved` with `approved`, so the list is `[self-hosted, approved]`.",
      "Do not add any other labels."
    ],
    "doneWhen": "The scan job asks for exactly `self-hosted` and `approved`.",
    "task": "Run the scan only on a self-hosted computer marked approved.",
    "editLocation": "Replace the value of `runs-on:` inside the `scan` job.",
    "keep": "Keep the scan command and use only the two required labels.",
    "editExample": "runs-on: [self-hosted, approved]",
    "example": "",
    "starter": "name: runner\non:\n  workflow_dispatch:\n    {}\njobs:\n  scan:\n    runs-on:\n      - self-hosted\n      - unapproved\n    steps:\n      - run: echo scan\n",
    "solution": "name: runner\non:\n  workflow_dispatch:\n    {}\njobs:\n  scan:\n    runs-on:\n      - self-hosted\n      - approved\n    steps:\n      - run: echo scan\n",
    "file": "workflow.yml",
    "hint": "Replace the value of `runs-on:` inside the `scan` job.",
    "success": "The scan job asks for exactly `self-hosted` and `approved`.",
    "source": {
      "label": "Self-hosted runner labels",
      "url": "https://docs.github.com/actions/how-tos/manage-runners/self-hosted-runners/use-in-a-workflow"
    },
    "rules": [
      "runner-policy"
    ]
  },
  {
    "id": "13-least-privilege",
    "index": 13,
    "title": "Give the workflow only the access it needs",
    "stage": "Secure delivery",
    "summary": "Set repository permissions to read contents only.",
    "explanation": [
      "A token is a temporary credential GitHub gives a workflow. Permissions are the keys that say what that token may do.",
      "Safer workflows start with the smallest useful key. You will allow reading repository contents and nothing more.",
      "If a later job truly needs more access, make that choice visible and limited to that job instead of widening everything."
    ],
    "instructions": [
      "Find the top-level `permissions:` line.",
      "Replace `write-all` with `contents: read` below `permissions:`.",
      "Leave the `build` job and its command unchanged."
    ],
    "doneWhen": "The workflow can read repository contents but cannot write them.",
    "task": "Give this workflow permission to read repository files and nothing more.",
    "editLocation": "Replace the top-level `permissions: write-all` line.",
    "keep": "Keep the build job and its command unchanged.",
    "editExample": "permissions:\n  contents: read",
    "example": "",
    "starter": "name: scopes\non:\n  workflow_dispatch:\n    {}\npermissions: write-all\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "solution": "name: scopes\non:\n  workflow_dispatch:\n    {}\npermissions:\n  contents: read\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "file": "workflow.yml",
    "hint": "Replace the top-level `permissions: write-all` line.",
    "success": "The workflow can read repository contents but cannot write them.",
    "source": {
      "label": "Automatic token authentication",
      "url": "https://docs.github.com/actions/security-for-github-actions/security-guides/automatic-token-authentication"
    },
    "rules": [
      "least-privilege"
    ]
  },
  {
    "id": "14-oidc-job",
    "index": 14,
    "title": "Keep cloud login permission in one job",
    "stage": "Secure delivery",
    "summary": "Give only deploy the permission and environment it needs.",
    "explanation": [
      "OIDC is a way for a job to ask a cloud provider for a short-lived identity instead of storing a long-lived secret. It is powerful, so it should stay in the one job that needs it.",
      "An environment is a named deployment target such as production. You will keep normal read access at the workflow level and put the special cloud permission on deploy.",
      "Production rules and cloud trust are configured outside this file; this workflow declares the narrow job that may request that identity."
    ],
    "instructions": [
      "At the top level, replace the current permissions with `contents: read`.",
      "Inside the `deploy` job, add `environment: production` and a `permissions:` section containing `id-token: write` and `contents: read`.",
      "Leave the deploy runner and command unchanged."
    ],
    "doneWhen": "Only deploy can request the cloud sign-in permission, and it targets production.",
    "task": "Give only the deploy job the extra permission it needs to sign in to the cloud.",
    "editLocation": "Change top-level `permissions:`, then add an environment and permissions inside the `deploy` job.",
    "keep": "Keep the deploy runner and command unchanged.",
    "editExample": "environment: production\npermissions:\n  id-token: write\n  contents: read",
    "example": "",
    "starter": "name: deploy\non:\n  workflow_dispatch:\n    {}\npermissions:\n  id-token: write\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo deploy\n",
    "solution": "name: deploy\non:\n  workflow_dispatch:\n    {}\npermissions:\n  contents: read\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    environment: production\n    permissions:\n      id-token: write\n      contents: read\n    steps:\n      - run: echo deploy\n",
    "file": "workflow.yml",
    "hint": "Change top-level `permissions:`, then add an environment and permissions inside the `deploy` job.",
    "success": "Only deploy can request the cloud sign-in permission, and it targets production.",
    "source": {
      "label": "OIDC with cloud providers",
      "url": "https://docs.github.com/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-cloud-providers"
    },
    "rules": [
      "oidc-deploy"
    ]
  },
  {
    "id": "15-sha-pin",
    "index": 15,
    "title": "Use an exact action version you can review",
    "stage": "Secure delivery",
    "summary": "Replace the moving checkout tag with the verified full commit SHA.",
    "explanation": [
      "An action reference can point to a moving tag such as v4, or to one exact commit. A SHA is the long unique identifier for that exact commit.",
      "Using the full verified SHA makes later reviews reproducible: everyone can see exactly what code the workflow chose.",
      "You will copy the approved SHA already noted in the starter file, not invent a new one."
    ],
    "instructions": [
      "Find `actions/checkout@v4` in the `build` job.",
      "Replace `v4` with the full commit value in the comment above the job.",
      "Leave `actions/checkout@` before that value, and do not add anything after the 40-character value."
    ],
    "doneWhen": "Checkout uses the exact approved 40-character commit value.",
    "task": "Use the exact approved checkout version instead of the moving `v4` label.",
    "editLocation": "In the `uses:` line of the checkout step in the `build` job.",
    "keep": "Keep `actions/checkout@` and copy the full value from the comment unchanged.",
    "editExample": "",
    "example": "",
    "starter": "name: pin\non:\n  workflow_dispatch:\n    {}\n# Verified checkout release commit for this exercise: 11bd71901bbe5b1630ceea73d27597364c9af683\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n",
    "solution": "name: pin\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683'\n",
    "file": "workflow.yml",
    "hint": "In the `uses:` line of the checkout step in the `build` job.",
    "success": "Checkout uses the exact approved 40-character commit value.",
    "source": {
      "label": "Secure use reference",
      "url": "https://docs.github.com/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions"
    },
    "rules": [
      "checkout-sha"
    ]
  },
  {
    "id": "16-upload-artifact",
    "index": 16,
    "title": "Save a build result for later",
    "stage": "Secure delivery",
    "summary": "Upload the dist folder as a named build artifact.",
    "explanation": [
      "An artifact is a file or folder saved after a workflow run. It is useful for build output, logs, or files another job needs to inspect.",
      "You will give the saved output a clear name and point it at the dist folder.",
      "A clear artifact name makes it easier to find the right build result when several jobs or runs exist."
    ],
    "instructions": [
      "Find the `steps:` list in the `build` job.",
      "Add a new step after the existing command using `actions/upload-artifact@v4`.",
      "Inside that new step, set `name: build-output` and `path: dist` under `with:`."
    ],
    "doneWhen": "The build saves `dist` with the name `build-output`.",
    "task": "Save the `dist` folder from the build with the name `build-output`.",
    "editLocation": "Inside the `steps:` list in the `build` job, after the existing command.",
    "keep": "Keep the command that creates `dist` unchanged.",
    "editExample": "- uses: actions/upload-artifact@v4\n  with:\n    name: build-output\n    path: dist",
    "example": "",
    "starter": "name: artifact\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'mkdir -p dist && echo hi > dist/result.txt'\n",
    "solution": "name: artifact\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'mkdir -p dist && echo hi > dist/result.txt'\n      - uses: actions/upload-artifact@v4\n        with:\n          name: build-output\n          path: dist\n",
    "file": "workflow.yml",
    "hint": "Inside the `steps:` list in the `build` job, after the existing command.",
    "success": "The build saves `dist` with the name `build-output`.",
    "source": {
      "label": "Storing workflow data as artifacts",
      "url": "https://docs.github.com/actions/using-workflows/storing-workflow-data-as-artifacts"
    },
    "rules": [
      "artifact"
    ]
  },
  {
    "id": "17-capstone-gate",
    "index": 17,
    "title": "Stop deployment until the build succeeds",
    "stage": "Secure delivery",
    "summary": "Make deploy wait for build while keeping read-only access.",
    "explanation": [
      "A deployment should not start before its required build is finished. A dependency is the explicit link that makes one job wait for another.",
      "You will add that gate and keep the deployment job’s permissions small. This combines ordering and access control from earlier lessons.",
      "This is the pattern to carry forward: say what must finish first, then give the next job only the access it needs."
    ],
    "instructions": [
      "Find the `deploy` job.",
      "Add `needs: build` inside it, on a new line lined up with `runs-on:`.",
      "Change its `contents` permission from `write` to `read`; leave the build job unchanged."
    ],
    "doneWhen": "Deploy waits for build and can read repository contents but cannot write them.",
    "task": "Make deployment wait for the build and keep deployment read-only.",
    "editLocation": "Inside the `deploy` job, on new lines lined up with `runs-on:`.",
    "keep": "Keep the `build` job and the deploy command unchanged.",
    "editExample": "needs: build\npermissions:\n  contents: read",
    "example": "",
    "starter": "name: gate\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo build\n  deploy:\n    runs-on: ubuntu-latest\n    permissions:\n      contents: write\n    steps:\n      - run: echo deploy\n",
    "solution": "name: gate\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo build\n  deploy:\n    needs: build\n    runs-on: ubuntu-latest\n    permissions:\n      contents: read\n    steps:\n      - run: echo deploy\n",
    "file": "workflow.yml",
    "hint": "Inside the `deploy` job, on new lines lined up with `runs-on:`.",
    "success": "Deploy waits for build and can read repository contents but cannot write them.",
    "source": {
      "label": "Defining prerequisite jobs",
      "url": "https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idneeds"
    },
    "rules": [
      "deploy-gate"
    ]
  }
];
