// Generated by scripts/build-course.mjs; do not hand-edit.
export const lessons = [
  {
    "id": "01-first-workflow",
    "index": 1,
    "title": "Make a workflow you can start yourself",
    "stage": "Foundations",
    "summary": "Tell GitHub exactly when this small automation recipe may run.",
    "explanation": [
      "A workflow is a recipe GitHub follows. An event is the bell that tells GitHub to start reading that recipe; a job is one group of work, and a step is one command inside it.",
      "Here you will add a manual event. It gives a person a Run workflow button, which is useful for a check that should only happen when somebody asks for it.",
      "Keep the existing build job: its runner chooses the computer, and its step is the command that computer will perform."
    ],
    "instructions": [
      "Find the top-level `on: false` line.",
      "Replace it with `on:` and add the indented line `workflow_dispatch: {}` beneath it.",
      "Keep the existing `jobs.build` job and its step unchanged."
    ],
    "doneWhen": "The YAML has a workflow_dispatch mapping and still has a valid build job.",
    "task": "Imagine you maintain a release smoke test. It must never run by accident; a maintainer should start it from the Actions page. In workflow.yml, replace the disabled on: false with a two-space-indented workflow_dispatch mapping. Keep the existing build job.",
    "example": "name: greeting\n\non:\n  workflow_dispatch: {}\n\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "starter": "name: first\non: false\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "solution": "name: first\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "file": "workflow.yml",
    "hint": "Events belong under the top-level trigger key; consult event syntax for the required mapping form.",
    "success": "Manual trigger is a mapping.",
    "source": {
      "label": "GitHub’s event documentation",
      "url": "https://docs.github.com/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow"
    },
    "rules": [
      "workflow_dispatch"
    ]
  },
  {
    "id": "02-job-and-runner",
    "index": 2,
    "title": "Choose the computer that runs your job",
    "stage": "Foundations",
    "summary": "Tell GitHub to run these commands on an Ubuntu machine.",
    "explanation": [
      "A job needs a computer before it can do any work. GitHub calls that computer a runner.",
      "GitHub can provide a fresh Ubuntu runner for common tasks. You will name that runner for the build job.",
      "The runs-on setting belongs inside the job; the steps underneath are the commands that runner will perform."
    ],
    "instructions": [
      "Find the `jobs.build` mapping.",
      "Add `runs-on: ubuntu-latest` inside build, aligned with `steps`.",
      "Keep the existing build step."
    ],
    "doneWhen": "The build job names ubuntu-latest as its runner.",
    "task": "Your team needs its small build check to run on GitHub’s Ubuntu image. In workflow.yml, add runs-on: ubuntu-latest to jobs.build, before steps and aligned with it.",
    "example": "",
    "starter": "name: runner\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    steps:\n      - run: echo build\n",
    "solution": "name: runner\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo build\n",
    "file": "workflow.yml",
    "hint": "A job declares the execution environment before it can run steps.",
    "success": "build uses ubuntu-latest.",
    "source": {
      "label": "Choose runners",
      "url": "https://docs.github.com/actions/how-tos/write-workflows/choose-where-workflows-run/choose-the-runner-for-a-job"
    },
    "rules": [
      "build-ubuntu"
    ]
  },
  {
    "id": "03-push-filter",
    "index": 3,
    "title": "Run only for the changes that matter",
    "stage": "Foundations",
    "summary": "Limit this workflow to main-branch changes under src/.",
    "explanation": [
      "A push event can happen for many branches and many files. Filters let a workflow ignore changes that do not need this particular check.",
      "You will keep this workflow focused on the main branch and source-code files. That avoids spending time on unrelated edits.",
      "Put both filters below the push event: branch filters choose a branch, while path filters choose files."
    ],
    "instructions": [
      "Find the top-level `on.push` event.",
      "Add `branches: [main]` and `paths: [src/**]` inside that push mapping.",
      "Keep both filters under push, not beside it."
    ],
    "doneWhen": "Push is limited to main and src/** changes.",
    "task": "The build should run only when src/ changes on main. In workflow.yml, keep the existing main branch filter and add a paths list containing exactly src/**, nested under push.",
    "example": "",
    "starter": "name: filter\non:\n  push:\n    branches:\n      - main\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "solution": "name: filter\non:\n  push:\n    branches:\n      - main\n    paths:\n      - 'src/**'\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "file": "workflow.yml",
    "hint": "Filters refine a single event and must be nested with that event's configuration.",
    "success": "push filters main and src/**.",
    "source": {
      "label": "Workflow filters",
      "url": "https://docs.github.com/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore"
    },
    "rules": [
      "push-filter"
    ]
  },
  {
    "id": "04-context-as-data",
    "index": 4,
    "title": "Handle event information safely",
    "stage": "Foundations",
    "summary": "Put event text in an environment variable before using it in a command.",
    "explanation": [
      "GitHub provides context values such as the text from an event. Treat that text like input from outside your script: it may contain spaces or special shell characters.",
      "An environment variable is a named value a command can read. You will pass the event text through one and quote it before printing it.",
      "Quoting \"$EVENT_TEXT\" keeps the shell from splitting one message into unexpected pieces."
    ],
    "instructions": [
      "Find the `inspect` step that prints event text directly.",
      "Add `env.EVENT_TEXT` with the GitHub event expression.",
      "Change the command to print quoted `$EVENT_TEXT` and remove direct event interpolation from `run`."
    ],
    "doneWhen": "Event text crosses an environment-variable boundary and is quoted in the command.",
    "task": "An issue title is being inspected by a workflow. In workflow.yml, give the inspect step an env mapping with EVENT_TEXT set from github.event, then make its run command echo \"$EVENT_TEXT\". Remove direct github.event interpolation from run.",
    "example": "",
    "starter": "name: context\non:\n  workflow_dispatch:\n    {}\njobs:\n  inspect:\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'echo ${{ github.event.issue.title }}'\n",
    "solution": "name: context\non:\n  workflow_dispatch:\n    {}\njobs:\n  inspect:\n    runs-on: ubuntu-latest\n    steps:\n      - env:\n          EVENT_TEXT: '${{ github.event.issue.title }}'\n        run: 'printf \"%s\\\\n\" \"$EVENT_TEXT\"'\n",
    "file": "workflow.yml",
    "hint": "Treat context as untrusted data: pass it through an environment boundary and quote shell expansion.",
    "success": "No direct context interpolation in run.",
    "source": {
      "label": "Contexts",
      "url": "https://docs.github.com/actions/learn-github-actions/contexts"
    },
    "rules": [
      "safe-env"
    ]
  },
  {
    "id": "05-job-output",
    "index": 5,
    "title": "Pass one result from a job",
    "stage": "Connect jobs",
    "summary": "Share the version from prepare with another job.",
    "explanation": [
      "Jobs are separate pieces of work. A value made in one job does not automatically appear in the next one.",
      "An output is a named result a job deliberately shares. You will connect a step output to a job output named version.",
      "Think of it as a two-part label: the step writes version first, then the job exposes that named value."
    ],
    "instructions": [
      "Find the `prepare` job and its version step.",
      "Give that step the id `version` and write its value to `$GITHUB_OUTPUT`.",
      "Add `prepare.outputs.version` that points at `steps.version.outputs.version`."
    ],
    "doneWhen": "Prepare exposes version from its named step output.",
    "task": "prepare calculates version 1; make it available to a future deployment. In workflow.yml, add outputs.version to prepare with the value ${{ steps.version.outputs.version }}. Leave the existing step that writes version=1 to $GITHUB_OUTPUT.",
    "example": "",
    "starter": "name: output\non:\n  workflow_dispatch:\n    {}\njobs:\n  prepare:\n    runs-on: ubuntu-latest\n    steps:\n      - id: version\n        run: 'echo version=1 >> \"$GITHUB_OUTPUT\"'\n",
    "solution": "name: output\non:\n  workflow_dispatch:\n    {}\njobs:\n  prepare:\n    runs-on: ubuntu-latest\n    outputs:\n      version: '${{ steps.version.outputs.version }}'\n    steps:\n      - id: version\n        run: 'echo version=1 >> \"$GITHUB_OUTPUT\"'\n",
    "file": "workflow.yml",
    "hint": "A value leaving a job needs an explicit step-to-job output bridge.",
    "success": "prepare maps version from a step output.",
    "source": {
      "label": "Passing job outputs",
      "url": "https://docs.github.com/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs"
    },
    "rules": [
      "job-output"
    ]
  },
  {
    "id": "06-needs-output",
    "index": 6,
    "title": "Use a result from an earlier job",
    "stage": "Connect jobs",
    "summary": "Make report wait for prepare and print its version.",
    "explanation": [
      "A later job must say which earlier job it depends on. GitHub calls that relationship needs.",
      "Once the dependency exists, the later job can read a named output from the earlier one. You will write both parts of that handoff.",
      "Write `needs: prepare` to set the order, then use the prepare output where report prints its message."
    ],
    "instructions": [
      "Find the `prepare` job and give its producing step id `v`.",
      "Expose `prepare.outputs.version` from `steps.v.outputs.version`.",
      "In `report`, add `needs: prepare` and print `needs.prepare.outputs.version`."
    ],
    "doneWhen": "Report depends on prepare and reads its version output.",
    "task": "The release report must wait for prepare and print its version. In workflow.yml, set report.needs to prepare, then change its command so it contains needs.prepare.outputs.version. The output bridge in prepare is already correct.",
    "example": "",
    "starter": "name: needs\non:\n  workflow_dispatch:\n    {}\njobs:\n  prepare:\n    runs-on: ubuntu-latest\n    outputs:\n      version: '${{ steps.v.outputs.version }}'\n    steps:\n      - id: v\n        run: 'echo version=1 >> \"$GITHUB_OUTPUT\"'\n  report:\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'echo missing'\n",
    "solution": "name: needs\non:\n  workflow_dispatch:\n    {}\njobs:\n  prepare:\n    runs-on: ubuntu-latest\n    outputs:\n      version: '${{ steps.v.outputs.version }}'\n    steps:\n      - id: v\n        run: 'echo version=1 >> \"$GITHUB_OUTPUT\"'\n  report:\n    needs: prepare\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'echo ${{ needs.prepare.outputs.version }}'\n",
    "file": "workflow.yml",
    "hint": "Cross-job data is available only after an explicit dependency and output declaration.",
    "success": "report depends on prepare and uses its output.",
    "source": {
      "label": "Job dependencies and outputs",
      "url": "https://docs.github.com/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs"
    },
    "rules": [
      "needs-output"
    ]
  },
  {
    "id": "07-matrix",
    "index": 7,
    "title": "Repeat a job for more than one version",
    "stage": "Connect jobs",
    "summary": "Repeat this job for the values 20 and 22.",
    "explanation": [
      "A matrix is a list that tells GitHub to repeat the same job with different values. It is a simple way to cover more than one supported version.",
      "You will add two Node values. GitHub would create one job variation for each value in a real run.",
      "A matrix supplies values; it does not install Node by itself. A later step would use each value to choose an installed version."
    ],
    "instructions": [
      "Find the `test` job.",
      "Add `strategy.matrix.node` under that job.",
      "Put both values, 20 and 22, in the node list."
    ],
    "doneWhen": "The matrix contains both 20 and 22.",
    "task": "The project supports Node 20 and 22. In workflow.yml, add 22 to the strategy.matrix.node list; keep 20 too.",
    "example": "",
    "starter": "name: matrix\non:\n  workflow_dispatch:\n    {}\njobs:\n  test:\n    runs-on: ubuntu-latest\n    strategy:\n      matrix:\n        node:\n          - 20\n    steps:\n      - run: echo test\n",
    "solution": "name: matrix\non:\n  workflow_dispatch:\n    {}\njobs:\n  test:\n    runs-on: ubuntu-latest\n    strategy:\n      matrix:\n        node:\n          - 20\n          - 22\n    steps:\n      - run: echo test\n",
    "file": "workflow.yml",
    "hint": "A matrix creates one job variation for every listed value.",
    "success": "Matrix contains 20 and 22.",
    "source": {
      "label": "Matrix strategy",
      "url": "https://docs.github.com/actions/using-jobs/using-a-matrix-for-your-jobs"
    },
    "rules": [
      "node-matrix"
    ]
  },
  {
    "id": "08-service-linux",
    "index": 8,
    "title": "Give a job a temporary Redis helper",
    "stage": "Connect jobs",
    "summary": "Run the test job on Ubuntu with a healthy Redis service.",
    "explanation": [
      "Some tests need a helper program such as Redis. A service is a temporary helper container that lives alongside one job.",
      "You will use an Ubuntu runner and add a health check so the job waits for Redis to be ready.",
      "The health command answers one important question before tests begin: is the helper ready to accept work?"
    ],
    "instructions": [
      "Find the `test` job and set `runs-on: ubuntu-latest`.",
      "Add a `services.redis` mapping with image `redis:7`.",
      "Add Redis options containing a `health-cmd` readiness check."
    ],
    "doneWhen": "The Ubuntu test job includes Redis with a health command.",
    "task": "The test job uses Redis 7. In workflow.yml, keep image: redis:7 and add options under redis containing a Redis health-cmd (for example redis-cli ping).",
    "example": "",
    "starter": "name: service\non:\n  workflow_dispatch:\n    {}\njobs:\n  test:\n    runs-on: ubuntu-latest\n    services:\n      redis:\n        image: redis:7\n    steps:\n      - run: echo test\n",
    "solution": "name: service\non:\n  workflow_dispatch:\n    {}\njobs:\n  test:\n    runs-on: ubuntu-latest\n    services:\n      redis:\n        image: redis:7\n        options: '--health-cmd \"redis-cli ping\"'\n    steps:\n      - run: echo test\n",
    "file": "workflow.yml",
    "hint": "Services share a job's lifecycle, so readiness and runner compatibility matter.",
    "success": "Ubuntu job has healthy Redis service.",
    "source": {
      "label": "Service containers",
      "url": "https://docs.github.com/actions/using-containerized-services/about-service-containers"
    },
    "rules": [
      "healthy-redis"
    ]
  },
  {
    "id": "09-reusable-call",
    "index": 9,
    "title": "Call a shared workflow",
    "stage": "Reuse and debug",
    "summary": "Use the organization’s reusable risk workflow and keep its input.",
    "explanation": [
      "A reusable workflow is a complete workflow another workflow can call. It is different from an ordinary job with its own runner and steps.",
      "You will point the risk job at the shared workflow and keep the sample-size setting it needs.",
      "The called workflow owns its own runner and steps, so this job only names what to call and the value to pass in."
    ],
    "instructions": [
      "Find the `risk` job.",
      "Remove its `runs-on` and `steps` fields.",
      "Add `uses: ./.github/workflows/reusable-risk.yml` and keep `with.sample_size: 3`."
    ],
    "doneWhen": "Risk calls the approved reusable workflow with sample size 3.",
    "task": "Your organization provides a shared risk check. In workflow.yml, make risk use ./.github/workflows/reusable-risk.yml. Keep with.sample_size: 3, and remove its runner and steps.",
    "example": "",
    "starter": "name: reuse\non:\n  workflow_dispatch:\n    {}\njobs:\n  risk:\n    with:\n      sample_size: 3\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo replace\n",
    "solution": "name: reuse\non:\n  workflow_dispatch:\n    {}\njobs:\n  risk:\n    uses: './.github/workflows/reusable-risk.yml'\n    with:\n      sample_size: 3\n",
    "file": "workflow.yml",
    "hint": "A reusable-workflow call is a job reference, not a runner-backed sequence of steps.",
    "success": "risk calls the approved reusable path and keeps sample_size 3.",
    "source": {
      "label": "Reusing workflows",
      "url": "https://docs.github.com/actions/sharing-automations/reusing-workflows"
    },
    "rules": [
      "reusable-call"
    ]
  },
  {
    "id": "10-composite-action",
    "index": 10,
    "title": "Describe a small reusable action",
    "stage": "Reuse and debug",
    "summary": "Declare a composite action with one safe shell step.",
    "explanation": [
      "An action is reusable automation. A composite action is the simplest kind: it groups normal workflow steps behind one name.",
      "You will say that this action uses the composite model and give its command an explicit shell.",
      "Naming bash makes the command’s language clear, which helps the action behave consistently for every caller."
    ],
    "instructions": [
      "Find the top-level `runs` mapping.",
      "Set `runs.using: composite`.",
      "Add one item in `runs.steps` with `shell: bash` and a command containing `echo hello`."
    ],
    "doneWhen": "The action declares composite runs and a bash echo step.",
    "task": "Turn action.yml into a tiny reusable greeting action: set runs.using to composite, add runs.steps, and include one Bash shell step that runs echo hello.",
    "example": "",
    "starter": "name: hello\nruns:\n  using: node20\n",
    "solution": "name: hello\nruns:\n  using: composite\n  steps:\n    - run: 'echo hello'\n      shell: bash\n",
    "file": "action.yml",
    "hint": "Composite actions describe their execution model and explicitly declare shells for run steps.",
    "success": "Composite action has a safe echo step.",
    "source": {
      "label": "Composite actions",
      "url": "https://docs.github.com/actions/sharing-automations/creating-actions/creating-a-composite-action"
    },
    "rules": [
      "composite"
    ]
  },
  {
    "id": "11-failure-evidence",
    "index": 11,
    "title": "Keep useful notes when a job fails",
    "stage": "Reuse and debug",
    "summary": "Write diagnostic evidence even after an earlier test step fails.",
    "explanation": [
      "When a job fails, the most useful details can disappear unless you save them. A job summary is a note shown with a GitHub Actions run.",
      "You will use always() so the evidence step still runs, then write its note to the summary file.",
      "That note gives the next person a quick place to start instead of making them search every log line."
    ],
    "instructions": [
      "Find the evidence-writing step in the `test` job.",
      "Set its `if` value to `always()` so it still runs after failure.",
      "Write its message to `$GITHUB_STEP_SUMMARY`."
    ],
    "doneWhen": "The evidence step uses always() and writes to the job summary.",
    "task": "The test intentionally fails, but its logs still need a short summary. In workflow.yml, add a later step whose if is exactly ${{ always() }} and whose run appends text to $GITHUB_STEP_SUMMARY.",
    "example": "",
    "starter": "name: evidence\non:\n  workflow_dispatch:\n    {}\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'exit 1'\n",
    "solution": "name: evidence\non:\n  workflow_dispatch:\n    {}\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'exit 1'\n      - if: '${{ always() }}'\n        name: evidence\n        run: 'echo evidence >> \"$GITHUB_STEP_SUMMARY\"'\n",
    "file": "workflow.yml",
    "hint": "Diagnostic work must be allowed to run after a failing earlier step and preserve its result.",
    "success": "Evidence step uses always() and GITHUB_STEP_SUMMARY.",
    "source": {
      "label": "Status check functions",
      "url": "https://docs.github.com/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions"
    },
    "rules": [
      "failure-evidence"
    ]
  },
  {
    "id": "12-runner-policy",
    "index": 12,
    "title": "Use only approved self-hosted computers",
    "stage": "Secure delivery",
    "summary": "Label the scan job with self-hosted and approved.",
    "explanation": [
      "Some organizations run their own computers instead of GitHub-hosted runners. Labels are short names GitHub uses to choose a matching computer.",
      "You will require both the self-hosted label and the organization’s approved label.",
      "Using both labels narrows the match. Runner groups and repository access decide whether the job is actually permitted to use that computer."
    ],
    "instructions": [
      "Find the `scan` job runner setting.",
      "Replace it with the list `[self-hosted, approved]`.",
      "Do not add other runner labels."
    ],
    "doneWhen": "Scan has exactly self-hosted and approved runner labels.",
    "task": "The scanning job must land only on approved self-hosted machines. In workflow.yml, make runs-on exactly the two-item list self-hosted and approved.",
    "example": "",
    "starter": "name: runner\non:\n  workflow_dispatch:\n    {}\njobs:\n  scan:\n    runs-on:\n      - self-hosted\n      - unapproved\n    steps:\n      - run: echo scan\n",
    "solution": "name: runner\non:\n  workflow_dispatch:\n    {}\njobs:\n  scan:\n    runs-on:\n      - self-hosted\n      - approved\n    steps:\n      - run: echo scan\n",
    "file": "workflow.yml",
    "hint": "Runner labels express scheduling requirements; restrict them to the approved policy vocabulary.",
    "success": "Runner labels are exactly approved/self-hosted.",
    "source": {
      "label": "Self-hosted runner labels",
      "url": "https://docs.github.com/actions/how-tos/manage-runners/self-hosted-runners/use-in-a-workflow"
    },
    "rules": [
      "runner-policy"
    ]
  },
  {
    "id": "13-least-privilege",
    "index": 13,
    "title": "Give the workflow only the access it needs",
    "stage": "Secure delivery",
    "summary": "Set repository permissions to read contents only.",
    "explanation": [
      "A token is a temporary credential GitHub gives a workflow. Permissions are the keys that say what that token may do.",
      "Safer workflows start with the smallest useful key. You will allow reading repository contents and nothing more.",
      "If a later job truly needs more access, make that choice visible and limited to that job instead of widening everything."
    ],
    "instructions": [
      "Find the top-level `permissions` mapping.",
      "Set it to exactly `contents: read`.",
      "Remove any broader job-level permissions or make them exactly the same read-only mapping."
    ],
    "doneWhen": "All declared permissions are exactly contents: read.",
    "task": "This build only reads repository content. In workflow.yml, replace the broad permission with a top-level mapping that contains exactly contents: read. Do not add job-level permissions.",
    "example": "",
    "starter": "name: scopes\non:\n  workflow_dispatch:\n    {}\npermissions: write-all\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "solution": "name: scopes\non:\n  workflow_dispatch:\n    {}\npermissions:\n  contents: read\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ready\n",
    "file": "workflow.yml",
    "hint": "Start from the smallest token capability and avoid broadening it in individual jobs.",
    "success": "Top-level permissions are exactly contents: read.",
    "source": {
      "label": "Automatic token authentication",
      "url": "https://docs.github.com/actions/security-for-github-actions/security-guides/automatic-token-authentication"
    },
    "rules": [
      "least-privilege"
    ]
  },
  {
    "id": "14-oidc-job",
    "index": 14,
    "title": "Keep cloud login permission in one job",
    "stage": "Secure delivery",
    "summary": "Give only deploy the permission and environment it needs.",
    "explanation": [
      "OIDC is a way for a job to ask a cloud provider for a short-lived identity instead of storing a long-lived secret. It is powerful, so it should stay in the one job that needs it.",
      "An environment is a named deployment target such as production. You will keep normal read access at the workflow level and put the special cloud permission on deploy.",
      "Production rules and cloud trust are configured outside this file; this workflow declares the narrow job that may request that identity."
    ],
    "instructions": [
      "Set top-level permissions to `contents: read`.",
      "On `deploy`, add `environment: production`.",
      "Set only deploy job permissions to `id-token: write` and `contents: read`."
    ],
    "doneWhen": "Only deploy has OIDC permission and it targets production.",
    "task": "In workflow.yml, make the top-level permissions exactly contents: read. On deploy, add environment: production and a job-level permissions mapping containing id-token: write and contents: read.",
    "example": "",
    "starter": "name: deploy\non:\n  workflow_dispatch:\n    {}\npermissions:\n  id-token: write\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo deploy\n",
    "solution": "name: deploy\non:\n  workflow_dispatch:\n    {}\npermissions:\n  contents: read\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    environment: production\n    permissions:\n      id-token: write\n      contents: read\n    steps:\n      - run: echo deploy\n",
    "file": "workflow.yml",
    "hint": "Keep cloud identity at the narrowest job boundary and combine it with deployment protection.",
    "success": "Only deploy has OIDC and it targets production.",
    "source": {
      "label": "OIDC with cloud providers",
      "url": "https://docs.github.com/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-cloud-providers"
    },
    "rules": [
      "oidc-deploy"
    ]
  },
  {
    "id": "15-sha-pin",
    "index": 15,
    "title": "Use an exact action version you can review",
    "stage": "Secure delivery",
    "summary": "Replace the moving checkout tag with the verified full commit SHA.",
    "explanation": [
      "An action reference can point to a moving tag such as v4, or to one exact commit. A SHA is the long unique identifier for that exact commit.",
      "Using the full verified SHA makes later reviews reproducible: everyone can see exactly what code the workflow chose.",
      "You will copy the approved SHA already noted in the starter file, not invent a new one."
    ],
    "instructions": [
      "Find the checkout step in the `build` job.",
      "Replace `actions/checkout@v4` with the full approved SHA in the starter comment.",
      "Keep the action name and do not add text after the 40-character SHA."
    ],
    "doneWhen": "Checkout uses the one approved full SHA.",
    "task": "In workflow.yml, replace actions/checkout@v4 with the verified 40-character checkout SHA in the comment directly above the job. Keep actions/checkout@ before that SHA.",
    "example": "",
    "starter": "name: pin\non:\n  workflow_dispatch:\n    {}\n# Verified checkout release commit for this exercise: 11bd71901bbe5b1630ceea73d27597364c9af683\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n",
    "solution": "name: pin\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683'\n",
    "file": "workflow.yml",
    "hint": "Immutable references make action review reproducible; verify any candidate against its upstream release.",
    "success": "checkout uses one complete 40-character SHA and no suffix.",
    "source": {
      "label": "Secure use reference",
      "url": "https://docs.github.com/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions"
    },
    "rules": [
      "checkout-sha"
    ]
  },
  {
    "id": "16-upload-artifact",
    "index": 16,
    "title": "Save a build result for later",
    "stage": "Secure delivery",
    "summary": "Upload the dist folder as a named build artifact.",
    "explanation": [
      "An artifact is a file or folder saved after a workflow run. It is useful for build output, logs, or files another job needs to inspect.",
      "You will give the saved output a clear name and point it at the dist folder.",
      "A clear artifact name makes it easier to find the right build result when several jobs or runs exist."
    ],
    "instructions": [
      "Find the `build` job steps.",
      "Add an `actions/upload-artifact@v4` step.",
      "Set its `with.name` to `build-output` and `with.path` to `dist`."
    ],
    "doneWhen": "Build uploads dist as build-output.",
    "task": "The build already creates dist/result.txt. In workflow.yml, add a second build step using actions/upload-artifact@v4. Give it name: build-output and path: dist.",
    "example": "",
    "starter": "name: artifact\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'mkdir -p dist && echo hi > dist/result.txt'\n",
    "solution": "name: artifact\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: 'mkdir -p dist && echo hi > dist/result.txt'\n      - uses: actions/upload-artifact@v4\n        with:\n          name: build-output\n          path: dist\n",
    "file": "workflow.yml",
    "hint": "Artifacts preserve named build outputs for later inspection or jobs, unlike dependency caches.",
    "success": "Artifact name and path are exact.",
    "source": {
      "label": "Storing workflow data as artifacts",
      "url": "https://docs.github.com/actions/using-workflows/storing-workflow-data-as-artifacts"
    },
    "rules": [
      "artifact"
    ]
  },
  {
    "id": "17-capstone-gate",
    "index": 17,
    "title": "Stop deployment until the build succeeds",
    "stage": "Secure delivery",
    "summary": "Make deploy wait for build while keeping read-only access.",
    "explanation": [
      "A deployment should not start before its required build is finished. A dependency is the explicit link that makes one job wait for another.",
      "You will add that gate and keep the deployment job’s permissions small. This combines ordering and access control from earlier lessons.",
      "This is the pattern to carry forward: say what must finish first, then give the next job only the access it needs."
    ],
    "instructions": [
      "Find the `deploy` job.",
      "Add `needs: build` so deployment waits for the build job.",
      "Keep deploy permissions read-only; do not add any write permission."
    ],
    "doneWhen": "Deploy waits for build and has no write permission.",
    "task": "In workflow.yml, give deploy needs: build. Change its permissions.contents from write to read, with no other write permission.",
    "example": "",
    "starter": "name: gate\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo build\n  deploy:\n    runs-on: ubuntu-latest\n    permissions:\n      contents: write\n    steps:\n      - run: echo deploy\n",
    "solution": "name: gate\non:\n  workflow_dispatch:\n    {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo build\n  deploy:\n    needs: build\n    runs-on: ubuntu-latest\n    permissions:\n      contents: read\n    steps:\n      - run: echo deploy\n",
    "file": "workflow.yml",
    "hint": "Dependencies model required prior work; retain minimal credentials while the gate is evaluated.",
    "success": "deploy needs build and has no write permissions.",
    "source": {
      "label": "Defining prerequisite jobs",
      "url": "https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idneeds"
    },
    "rules": [
      "deploy-gate"
    ]
  }
];
