// Human-first course copy for the browser. Keep YAML tasks and validation in the manifest/fixtures.
export const courseCopy = {
  '01-first-workflow': ['Make a workflow you can start yourself', 'Tell GitHub exactly when this small automation recipe may run.', ['A workflow is a recipe GitHub follows. An event is the bell that tells GitHub to start reading that recipe; a job is one group of work, and a step is one command inside it.', 'Here you will add a manual event. It gives a person a Run workflow button, which is useful for a check that should only happen when somebody asks for it.', 'Keep the existing build job: its runner chooses the computer, and its step is the command that computer will perform.']],
  '02-job-and-runner': ['Choose the computer that runs your job', 'Tell GitHub to run these commands on an Ubuntu machine.', ['A job needs a computer before it can do any work. GitHub calls that computer a runner.', 'GitHub can provide a fresh Ubuntu runner for common tasks. You will name that runner for the build job.', 'The runs-on setting belongs inside the job; the steps underneath are the commands that runner will perform.']],
  '03-push-filter': ['Run only for the changes that matter', 'Limit this workflow to main-branch changes under src/.', ['A push event can happen for many branches and many files. Filters let a workflow ignore changes that do not need this particular check.', 'You will keep this workflow focused on the main branch and source-code files. That avoids spending time on unrelated edits.', 'Put both filters below the push event: branch filters choose a branch, while path filters choose files.']],
  '04-context-as-data': ['Handle event information safely', 'Put event text in an environment variable before using it in a command.', ['GitHub provides context values such as the text from an event. Treat that text like input from outside your script: it may contain spaces or special shell characters.', 'An environment variable is a named value a command can read. You will pass the event text through one and quote it before printing it.', 'Quoting "$EVENT_TEXT" keeps the shell from splitting one message into unexpected pieces.']],
  '05-job-output': ['Pass one result from a job', 'Share the version from prepare with another job.', ['Jobs are separate pieces of work. A value made in one job does not automatically appear in the next one.', 'An output is a named result a job deliberately shares. You will connect a step output to a job output named version.', 'Think of it as a two-part label: the step writes version first, then the job exposes that named value.']],
  '06-needs-output': ['Use a result from an earlier job', 'Make report wait for prepare and print its version.', ['A later job must say which earlier job it depends on. GitHub calls that relationship needs.', 'Once the dependency exists, the later job can read a named output from the earlier one. You will write both parts of that handoff.', 'Write `needs: prepare` to set the order, then use the prepare output where report prints its message.']],
  '07-matrix': ['Repeat a job for more than one version', 'Repeat this job for the values 20 and 22.', ['A matrix is a list that tells GitHub to repeat the same job with different values. It is a simple way to cover more than one supported version.', 'You will add two Node values. GitHub would create one job variation for each value in a real run.', 'A matrix supplies values; it does not install Node by itself. A later step would use each value to choose an installed version.']],
  '08-service-linux': ['Give a job a temporary Redis helper', 'Run the test job on Ubuntu with a healthy Redis service.', ['Some tests need a helper program such as Redis. A service is a temporary helper container that lives alongside one job.', 'You will use an Ubuntu runner and add a health check so the job waits for Redis to be ready.', 'The health command answers one important question before tests begin: is the helper ready to accept work?']],
  '09-reusable-call': ['Call a shared workflow', 'Use the organization’s reusable risk workflow and keep its input.', ['A reusable workflow is a complete workflow another workflow can call. It is different from an ordinary job with its own runner and steps.', 'You will point the risk job at the shared workflow and keep the sample-size setting it needs.', 'The called workflow owns its own runner and steps, so this job only names what to call and the value to pass in.']],
  '10-composite-action': ['Describe a small reusable action', 'Declare a composite action with one safe shell step.', ['An action is reusable automation. A composite action is the simplest kind: it groups normal workflow steps behind one name.', 'You will say that this action uses the composite model and give its command an explicit shell.', 'Naming bash makes the command’s language clear, which helps the action behave consistently for every caller.']],
  '11-failure-evidence': ['Keep useful notes when a job fails', 'Write diagnostic evidence even after an earlier test step fails.', ['When a job fails, the most useful details can disappear unless you save them. A job summary is a note shown with a GitHub Actions run.', 'You will use always() so the evidence step still runs, then write its note to the summary file.', 'That note gives the next person a quick place to start instead of making them search every log line.']],
  '12-runner-policy': ['Use only approved self-hosted computers', 'Label the scan job with self-hosted and approved.', ['Some organizations run their own computers instead of GitHub-hosted runners. Labels are short names GitHub uses to choose a matching computer.', 'You will require both the self-hosted label and the organization’s approved label.', 'Using both labels narrows the match. Runner groups and repository access decide whether the job is actually permitted to use that computer.']],
  '13-least-privilege': ['Give the workflow only the access it needs', 'Set repository permissions to read contents only.', ['A token is a temporary credential GitHub gives a workflow. Permissions are the keys that say what that token may do.', 'Safer workflows start with the smallest useful key. You will allow reading repository contents and nothing more.', 'If a later job truly needs more access, make that choice visible and limited to that job instead of widening everything.']],
  '14-oidc-job': ['Keep cloud login permission in one job', 'Give only deploy the permission and environment it needs.', ['OIDC is a way for a job to ask a cloud provider for a short-lived identity instead of storing a long-lived secret. It is powerful, so it should stay in the one job that needs it.', 'An environment is a named deployment target such as production. You will keep normal read access at the workflow level and put the special cloud permission on deploy.', 'Production rules and cloud trust are configured outside this file; this workflow declares the narrow job that may request that identity.']],
  '15-sha-pin': ['Use an exact action version you can review', 'Replace the moving checkout tag with the verified full commit SHA.', ['An action reference can point to a moving tag such as v4, or to one exact commit. A SHA is the long unique identifier for that exact commit.', 'Using the full verified SHA makes later reviews reproducible: everyone can see exactly what code the workflow chose.', 'You will copy the approved SHA already noted in the starter file, not invent a new one.']],
  '16-upload-artifact': ['Save a build result for later', 'Upload the dist folder as a named build artifact.', ['An artifact is a file or folder saved after a workflow run. It is useful for build output, logs, or files another job needs to inspect.', 'You will give the saved output a clear name and point it at the dist folder.', 'A clear artifact name makes it easier to find the right build result when several jobs or runs exist.']],
  '17-capstone-gate': ['Stop deployment until the build succeeds', 'Make deploy wait for build while keeping read-only access.', ['A deployment should not start before its required build is finished. A dependency is the explicit link that makes one job wait for another.', 'You will add that gate and keep the deployment job’s permissions small. This combines ordering and access control from earlier lessons.', 'This is the pattern to carry forward: say what must finish first, then give the next job only the access it needs.']]
};

export const courseInstructions = {
  '01-first-workflow': ['Find `on: false` near the top of the file.', 'Replace it with `on:`, then put `workflow_dispatch: {}` on the next line with two spaces before it.', 'Leave the `build` job and its command as they are.'],
  '02-job-and-runner': ['Find the `build` job under `jobs:`.', 'Inside `build`, add `runs-on: ubuntu-latest` on a new line lined up with `steps:`.', 'Leave the existing command in `steps:` unchanged.'],
  '03-push-filter': ['Find `push:` under `on:`.', 'Inside `push`, add `paths: [src/**]` on a new line lined up with `branches:`.', 'Leave `branches: [main]` and the `build` job unchanged.'],
  '04-context-as-data': ['Find the command in the `inspect` job that contains `${{ github.event.issue.title }}`.', 'In that same step, add `env:` and place `EVENT_TEXT: ${{ github.event.issue.title }}` below it with two more spaces.', 'Change the command to `printf "%s\\n" "$EVENT_TEXT"`; do not leave the GitHub value in the command.'],
  '05-job-output': ['Find the `prepare` job and the step with `id: version`.', 'Inside `prepare`, add `outputs:` with `version: ${{ steps.version.outputs.version }}` below it.', 'Leave the step id `version` and its line that writes to `$GITHUB_OUTPUT` unchanged.'],
  '06-needs-output': ['Find the `report` job.', 'Inside `report`, add `needs: prepare` on a new line lined up with `runs-on:`.', 'Change its command so it prints `${{ needs.prepare.outputs.version }}`. Leave the `prepare` job unchanged.'],
  '07-matrix': ['Find the `node` list inside the `test` job.', 'Add `22` after `20`, so the list is `[20, 22]`.', 'Leave the runner and test command unchanged.'],
  '08-service-linux': ['Find `services:` inside the `test` job.', 'Inside `redis`, add `options: --health-cmd "redis-cli ping"` on a new line lined up with `image:`.', 'Leave `runs-on: ubuntu-latest`, the Redis image, and the test command unchanged.'],
  '09-reusable-call': ['Find the `risk` job.', 'Replace its `runs-on:` and `steps:` lines with `uses: ./.github/workflows/reusable-risk.yml`.', 'Leave `with:` and `sample_size: 3` in the `risk` job.'],
  '10-composite-action': ['Find `runs:` in `action.yml`.', 'Change `using: node20` to `using: composite`, then add `steps:` below it.', 'Under `steps:`, add one step with `run: echo hello` and `shell: bash`.'],
  '11-failure-evidence': ['Find the `steps:` list in the `test` job.', 'Add a new step after the failing command with `if: ${{ always() }}` and a command that appends `evidence` to `$GITHUB_STEP_SUMMARY`.', 'Leave the existing `exit 1` command unchanged.'],
  '12-runner-policy': ['Find `runs-on:` in the `scan` job.', 'Replace `unapproved` with `approved`, so the list is `[self-hosted, approved]`.', 'Do not add any other labels.'],
  '13-least-privilege': ['Find the top-level `permissions:` line.', 'Replace `write-all` with `contents: read` below `permissions:`.', 'Leave the `build` job and its command unchanged.'],
  '14-oidc-job': ['At the top level, replace the current permissions with `contents: read`.', 'Inside the `deploy` job, add `environment: production` and a `permissions:` section containing `id-token: write` and `contents: read`.', 'Leave the deploy runner and command unchanged.'],
  '15-sha-pin': ['Find `actions/checkout@v4` in the `build` job.', 'Replace `v4` with the full commit value in the comment above the job.', 'Leave `actions/checkout@` before that value, and do not add anything after the 40-character value.'],
  '16-upload-artifact': ['Find the `steps:` list in the `build` job.', 'Add a new step after the existing command using `actions/upload-artifact@v4`.', 'Inside that new step, set `name: build-output` and `path: dist` under `with:`.'],
  '17-capstone-gate': ['Find the `deploy` job.', 'Add `needs: build` inside it, on a new line lined up with `runs-on:`.', 'Change its `contents` permission from `write` to `read`; leave the build job unchanged.']
};

export const courseTasks = {
  '01-first-workflow': { goal: 'Make this workflow run only when someone clicks Run workflow on GitHub.', location: 'Near the top of `workflow.yml`, replace the `on: false` line.', keep: 'Keep the whole `build` job and its command unchanged.', example: 'on:\n  workflow_dispatch: {}' },
  '02-job-and-runner': { goal: 'Choose the Ubuntu computer that runs the build job.', location: 'Inside the `build` job, on a new line lined up with `steps:`.', keep: 'Keep the existing build step unchanged.', example: 'runs-on: ubuntu-latest' },
  '03-push-filter': { goal: 'Run this workflow only when files in `src/` change on `main`.', location: 'Inside `push:`, on a new line lined up with `branches:`.', keep: 'Keep the existing `branches: [main]` filter and the build job.', example: 'paths: [src/**]' },
  '04-context-as-data': { goal: 'Put the issue title in a named value before printing it safely.', location: 'Inside the existing step in the `inspect` job, beside its `run:` line.', keep: 'Keep the `inspect` job and its runner.', example: 'env:\n  EVENT_TEXT: ${{ github.event.issue.title }}' },
  '05-job-output': { goal: 'Make the version created by `prepare` available to another job.', location: 'Inside the `prepare` job, on a new line lined up with `runs-on:` and `steps:`.', keep: 'Keep the existing `version` step and its `$GITHUB_OUTPUT` line.', example: 'outputs:\n  version: ${{ steps.version.outputs.version }}' },
  '06-needs-output': { goal: 'Make `report` wait for `prepare` and print its version.', location: 'Inside the `report` job, on new lines lined up with `runs-on:`.', keep: 'Keep the complete `prepare` job unchanged.', example: 'needs: prepare' },
  '07-matrix': { goal: 'Create two versions of the test job, one labeled Node 20 and one labeled Node 22.', location: 'Inside the existing `node` list in the `test` job.', keep: 'Keep the runner and the test command unchanged.', example: 'node: [20, 22]' },
  '08-service-linux': { goal: 'Make the test job wait until its Redis helper is ready.', location: 'Inside `redis:` under `services:` in the `test` job, on a new line lined up with `image:`.', keep: 'Keep the Ubuntu runner, Redis image, and test command unchanged.', example: 'options: --health-cmd "redis-cli ping"' },
  '09-reusable-call': { goal: 'Use the shared risk workflow for the `risk` job.', location: 'Inside the `risk` job, where `runs-on:` and `steps:` are now.', keep: 'Keep `with:` and `sample_size: 3` unchanged.', example: 'uses: ./.github/workflows/reusable-risk.yml' },
  '10-composite-action': { goal: 'Turn this action into a reusable action that says hello.', location: 'Under the top-level `runs:` section in `action.yml`.', keep: 'Keep the action name `hello` unchanged.', example: 'runs:\n  using: composite\n  steps:\n    - run: echo hello\n      shell: bash' },
  '11-failure-evidence': { goal: 'Save a short note even when the earlier test command fails.', location: 'Inside the `steps:` list in the `test` job, after the `exit 1` step.', keep: 'Keep the existing failing command unchanged.', example: '- if: ${{ always() }}\n  run: echo evidence >> "$GITHUB_STEP_SUMMARY"' },
  '12-runner-policy': { goal: 'Run the scan only on a self-hosted computer marked approved.', location: 'Replace the value of `runs-on:` inside the `scan` job.', keep: 'Keep the scan command and use only the two required labels.', example: 'runs-on: [self-hosted, approved]' },
  '13-least-privilege': { goal: 'Give this workflow permission to read repository files and nothing more.', location: 'Replace the top-level `permissions: write-all` line.', keep: 'Keep the build job and its command unchanged.', example: 'permissions:\n  contents: read' },
  '14-oidc-job': { goal: 'Give only the deploy job the extra permission it needs to sign in to the cloud.', location: 'Change top-level `permissions:`, then add an environment and permissions inside the `deploy` job.', keep: 'Keep the deploy runner and command unchanged.', example: 'environment: production\npermissions:\n  id-token: write\n  contents: read' },
  '15-sha-pin': { goal: 'Use the exact approved checkout version instead of the moving `v4` label.', location: 'In the `uses:` line of the checkout step in the `build` job.', keep: 'Keep `actions/checkout@` and copy the full value from the comment unchanged.', example: '' },
  '16-upload-artifact': { goal: 'Save the `dist` folder from the build with the name `build-output`.', location: 'Inside the `steps:` list in the `build` job, after the existing command.', keep: 'Keep the command that creates `dist` unchanged.', example: '- uses: actions/upload-artifact@v4\n  with:\n    name: build-output\n    path: dist' },
  '17-capstone-gate': { goal: 'Make deployment wait for the build and keep deployment read-only.', location: 'Inside the `deploy` job, on new lines lined up with `runs-on:`.', keep: 'Keep the `build` job and the deploy command unchanged.', example: 'needs: build\npermissions:\n  contents: read' }
};

export const courseOutcomes = {
  '01-first-workflow': 'GitHub shows a Run workflow button, and the build job is still present.',
  '02-job-and-runner': 'The build job is set to use an Ubuntu computer.',
  '03-push-filter': 'The workflow responds only to changes in `src/` on `main`.',
  '04-context-as-data': 'The issue title is saved as `EVENT_TEXT` before the command prints it.',
  '05-job-output': 'The `prepare` job makes its version available under the name `version`.',
  '06-needs-output': 'The report job waits for prepare and prints the version it made.',
  '07-matrix': 'The test job is set to run with both 20 and 22.',
  '08-service-linux': 'The test job has Redis and checks that Redis is ready.',
  '09-reusable-call': 'The risk job uses the shared workflow and keeps the sample size of 3.',
  '10-composite-action': 'The action is set up as a composite action with a Bash hello command.',
  '11-failure-evidence': 'The new note step runs even after a failure and saves a note in the run summary.',
  '12-runner-policy': 'The scan job asks for exactly `self-hosted` and `approved`.',
  '13-least-privilege': 'The workflow can read repository contents but cannot write them.',
  '14-oidc-job': 'Only deploy can request the cloud sign-in permission, and it targets production.',
  '15-sha-pin': 'Checkout uses the exact approved 40-character commit value.',
  '16-upload-artifact': 'The build saves `dist` with the name `build-output`.',
  '17-capstone-gate': 'Deploy waits for build and can read repository contents but cannot write them.'
};
