(function () {
  'use strict';
  var root = document.getElementById('app');
  var course = window.GH200Course;
  var STORE_KEY = 'actions-academy-gh200-v1';
  var state = { view: 'learning', selected: '', drafts: {}, completed: {}, phases: {}, passes: {}, practice: {}, practiceFilter: '', reviewWrong: false, reviewQueue: [], practiceIndex: 0, referenceSection: '' };

  function el(tag, attrs, children) {
    var node = document.createElement(tag); var key;
    attrs = attrs || {}; children = children == null ? [] : (Array.isArray(children) ? children : [children]);
    for (key in attrs) { if (attrs[key] == null || attrs[key] === false) continue; if (key === 'class') node.className = attrs[key]; else if (key === 'text') node.textContent = attrs[key]; else if (key.indexOf('on') === 0) node.addEventListener(key.slice(2), attrs[key]); else node.setAttribute(key, attrs[key]); }
    children.forEach(function (child) { node.append(child && child.nodeType ? child : document.createTextNode(String(child))); }); return node;
  }
  function questions() { return Array.isArray(course && course.questions) ? course.questions.filter(function (question) { return question && typeof question.id === 'string' && Array.isArray(question.options) && typeof question.correct === 'number' && question.correct >= 0 && question.correct < question.options.length; }) : []; }
  function references() { return Array.isArray(course && course.references) ? course.references.filter(function (reference) { return reference && typeof reference.id === 'string'; }) : []; }
  function load() { try { var parsed = JSON.parse(localStorage.getItem(STORE_KEY)); var known = lessons().map(orderedId); var knownQuestions = questions().map(function (question) { return question.id; }); if (!parsed || typeof parsed !== 'object') return; state.view = ['learning','practice','references'].indexOf(parsed.view) !== -1 ? parsed.view : 'learning'; state.selected = typeof parsed.selected === 'string' && (parsed.selected === '' || parsed.selected === 'complete' || known.indexOf(parsed.selected) !== -1) ? parsed.selected : ''; if (parsed.drafts && typeof parsed.drafts === 'object') Object.keys(parsed.drafts).forEach(function (id) { if (known.indexOf(id) !== -1 && typeof parsed.drafts[id] === 'string') state.drafts[id] = parsed.drafts[id]; }); if (parsed.completed && typeof parsed.completed === 'object') Object.keys(parsed.completed).forEach(function (id) { if (known.indexOf(id) !== -1 && parsed.completed[id] === true) state.completed[id] = true; }); if (parsed.phases && typeof parsed.phases === 'object') Object.keys(parsed.phases).forEach(function (id) { if (known.indexOf(id) !== -1 && ['learn','write','test','done'].indexOf(parsed.phases[id]) !== -1) state.phases[id] = parsed.phases[id]; }); if (parsed.practice && typeof parsed.practice === 'object') Object.keys(parsed.practice).forEach(function (id) { var answer = parsed.practice[id]; if (knownQuestions.indexOf(id) !== -1 && answer && typeof answer === 'object' && Number.isInteger(answer.choice) && answer.choice >= 0 && answer.choice < questions().filter(function (question) { return question.id === id; })[0].options.length && typeof answer.checked === 'boolean') state.practice[id] = { choice: answer.choice, checked: answer.checked }; }); if (typeof parsed.practiceFilter === 'string') state.practiceFilter = parsed.practiceFilter; state.reviewWrong = parsed.reviewWrong === true; if (Array.isArray(parsed.reviewQueue)) state.reviewQueue = parsed.reviewQueue.filter(function (id, index, list) { return knownQuestions.indexOf(id) !== -1 && list.indexOf(id) === index; }); if (Number.isInteger(parsed.practiceIndex) && parsed.practiceIndex >= 0) state.practiceIndex = parsed.practiceIndex; } catch (_) {} }
  function save() { try { localStorage.setItem(STORE_KEY, JSON.stringify({ view: state.view, selected: state.selected, drafts: state.drafts, completed: state.completed, phases: state.phases, practice: state.practice, practiceFilter: state.practiceFilter, reviewWrong: state.reviewWrong, reviewQueue: state.reviewQueue, practiceIndex: state.practiceIndex })); } catch (_) {} }
  function lessons() { return course.lessons || []; }
  function find(id) { return lessons().filter(function (lesson) { return orderedId(lesson) === id; })[0]; }
  function orderedId(lesson) { return String(lesson.index || lesson.id).padStart(2, '0').slice(0, 2); }
  function select(id) { state.selected = id; state.passes = {}; save(); render(); window.scrollTo(0, 0); }
  function doneCount() { return Object.keys(state.completed).length; }
  function focusLessonHeading() { var heading = document.querySelector('#main h1'); if (heading) { heading.tabIndex = -1; heading.focus({ preventScroll: true }); } }
  function refreshCompletionUI(id) {
    var count = doneCount(); var progress = document.getElementById('progress-count'); var tag = document.getElementById('lesson-status'); var step = document.getElementById('step-done'); var item = document.querySelector('[data-lesson-item="' + id + '"]'); var dot = document.querySelector('[data-lesson-dot="' + id + '"]'); var continueArea = document.getElementById('lesson-continue');
    if (progress) progress.textContent = count + ' of ' + lessons().length;
    if (tag) tag.textContent = state.completed[id] ? 'Completed' : 'Practice now';
    if (step) step.classList.toggle('ready', !!state.completed[id]);
    if (item) item.classList.toggle('done', !!state.completed[id]);
    if (dot) dot.textContent = state.completed[id] ? '✓' : id;
    var mapNode = document.querySelector('[data-map-lesson="' + id + '"]'); var mapState = document.querySelector('[data-map-state="' + id + '"]');
    if (mapNode) mapNode.classList.toggle('done', !!state.completed[id]);
    if (mapState) mapState.textContent = state.completed[id] ? 'Done' : 'Open lesson';
    if (!state.completed[id] && continueArea) continueArea.remove();
  }
  function setPhase(id, phase) { state.phases[id] = phase; save(); Array.prototype.forEach.call(document.querySelectorAll('[data-step]'), function (step) { var active = step.getAttribute('data-step') === phase; step.classList.toggle('active', active); if (active) step.setAttribute('aria-current', 'step'); else step.removeAttribute('aria-current'); }); }
  function showStep(id, phase, target) { setPhase(id, phase); var node = document.getElementById(target); if (node) node.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  function inlineText(text) { var fragment = document.createDocumentFragment(); String(text || '').split(/(`[^`]+`)/g).forEach(function (part) { if (part.charAt(0) === '`' && part.charAt(part.length - 1) === '`') fragment.append(el('code', { text:part.slice(1, -1) })); else fragment.append(document.createTextNode(part)); }); return fragment; }
  function button(text, className, handler, disabled, ariaLabel) { return el('button', { class: className, type: 'button', onclick: handler, disabled: disabled ? 'disabled' : null, 'aria-label': ariaLabel || null, text: text }); }
  function changeView(view, referenceSection) { state.view = view; state.referenceSection = referenceSection || ''; if (view !== 'learning') state.selected = ''; save(); render(); window.scrollTo(0, 0); focusLessonHeading(); }
  function header() { var nav = el('nav', { class:'top-nav', 'aria-label':'Course sections' }); [['learning','Learning path'],['practice','Practice questions'],['references','References']].forEach(function (item) { var link = button(item[1], 'top-nav-link', function () { changeView(item[0]); }); if (state.view === item[0]) link.setAttribute('aria-current', 'page'); nav.append(link); }); return el('header', { class: 'topbar' }, [el('a', { class: 'brand', href: '#', text: 'Actions Academy', onclick: function (e) { e.preventDefault(); state.view = 'learning'; state.selected = ''; save(); render(); focusLessonHeading(); } }, [el('small', { text: 'GH-200 practice' })]), nav, el('div', { class: 'progress' }, [el('strong', { id: 'progress-count', text: doneCount() + ' of ' + lessons().length }), ' lessons complete'])]); }
  function sidebar() { var nav = el('nav', { class: 'sidebar', 'aria-label': 'Course lessons' }); var list = el('ul', { class: 'stage-nav' }); var lastStage = '';
    lessons().forEach(function (lesson) { var id = orderedId(lesson); if (lesson.stage !== lastStage) { lastStage = lesson.stage; list.append(el('li', { class: 'stage-name', text: lesson.stage })); } var item = el('li', { class: state.completed[id] ? 'done' : '', 'data-lesson-item': id }); var b = button('', 'lesson-link', function () { select(id); focusLessonHeading(); }); b.setAttribute('aria-label', 'Lesson ' + id + ': ' + lesson.title); if (state.selected === id) b.setAttribute('aria-current', 'page'); b.append(el('span', { class: 'dot', 'data-lesson-dot': id, text: state.completed[id] ? '✓' : id }), el('span', { text: lesson.title })); item.append(b); list.append(item); });
    nav.append(el('p', { class: 'nav-title', text: 'Your learning path' }), list, el('a', { class: 'docs-link', href: 'docs/START_HERE.md', text: 'Course notes ↗' })); return nav;
  }
  function intro() { var section = el('section', { class: 'intro' }); section.append(el('p', { class: 'eyebrow', text: 'Hands-on practice' }), el('h1', { text: 'Your GitHub Actions learning path' }), el('p', { class: 'lede', text: 'Learn how GitHub can run tasks for you. Follow the boxes in order. In each lesson, read a short explanation, change a few lines of code, test your answer, and tick it off.' }), el('div', { class: 'button-row' }, [button('Start with lesson 01', 'primary', function () { select('01'); focusLessonHeading(); }), button('Browse the path', 'secondary', function () { document.getElementById('path').scrollIntoView({ behavior: 'smooth' }); })]));
    var concept = el('div', { class: 'concept', 'aria-label': 'How a workflow is structured' }); [['Workflow', 'a file that tells GitHub what to do'], ['Job', 'a set of tasks'], ['Step', 'one task'], ['Runner', 'a computer that does the tasks']].forEach(function (part) { concept.append(el('div', {}, [el('b', { text: part[0] }), el('span', { text: part[1] })])); }); section.append(concept);
    var path = el('div', { class: 'path', id: 'path', 'aria-label':'17 lesson learning map' }); var groups = []; lessons().forEach(function (lesson) { var group = groups.filter(function (item) { return item.stage === lesson.stage; })[0]; if (!group) { group = { stage: lesson.stage, lessons: [] }; groups.push(group); } group.lessons.push(lesson); }); groups.forEach(function (group, i) { var stage = el('section', { class:'flow-stage' }); stage.append(el('button', { class: 'stage-card', type: 'button', onclick: function(){ select(orderedId(group.lessons[0])); focusLessonHeading(); } }, [el('span', { class: 'stage-node', text: String(i + 1).padStart(2,'0') }), el('b', { text: group.stage }), el('span', { text: group.lessons.length + ' lessons' })])); var nodes = el('div', { class:'map-nodes' }); group.lessons.forEach(function (lesson) { var id = orderedId(lesson); var node = el('button', { class:'map-lesson' + (state.completed[id] ? ' done' : ''), type:'button', 'data-map-lesson':id, 'aria-label':'Lesson ' + id + ': ' + lesson.title + (state.completed[id] ? ', completed' : ''), onclick:function(){ select(id); focusLessonHeading(); } }); node.append(el('span', { class:'map-number', text:state.completed[id] ? '✓' : id }), el('span', { class:'map-copy' }, [el('b', { text:lesson.title }), el('small', { text:lesson.summary || 'Open this lesson.' })]), el('span', { class:'map-state', 'data-map-state':id, text:state.completed[id] ? 'Done' : 'Open lesson' })); nodes.append(node); }); stage.append(nodes); path.append(stage); }); section.append(el('div', { class: 'path-head' }, [el('div', {}, [el('p', { class: 'eyebrow', text: 'Four connected stages' }), el('h2', { text: 'Follow the flow' })]), el('span', { class: 'progress', text: 'Pick any lesson to revisit' })]), path); return section; }
  function feedback(result) { var box = el('section', { class: 'feedback ' + (result.passed ? '' : 'error'), role: 'status' }); box.append(el('p', { text: result.passed ? 'Looks good — this draft meets the exercise checks.' : 'Not quite yet — adjust the YAML and try again.' })); if (!result.passed && result.errors && result.errors.length) { var ul = el('ul'); result.errors.forEach(function (message) { ul.append(el('li', { text: message })); }); box.append(ul); } return box; }
  function lessonView(lesson) { var id = orderedId(lesson); var draft = Object.prototype.hasOwnProperty.call(state.drafts, id) ? state.drafts[id] : (lesson.starter || ''); var passed = state.passes[id] && state.passes[id].source === draft && state.passes[id].passed; var wrap = el('article');
    wrap.append(el('header', { class: 'lesson-head' }, [el('p', { class: 'eyebrow', text: 'Lesson ' + id + ' · ' + lesson.stage }), el('h1', { text: lesson.title }), el('p', { text: lesson.summary || '' }), el('span', { class: 'tag', id:'lesson-status', text: state.completed[id] ? 'Completed' : 'Practice now' })]));
    var phase = state.completed[id] ? 'done' : (state.phases[id] || 'learn'); var stepper = el('div', { class: 'stepper', 'aria-label': 'Lesson steps' }); [['learn','1 Learn','learn-card'],['write','2 Write','editor-card'],['test','3 Test','check-feedback'],['done','4 Done','mark-done']].forEach(function (s) { var current = phase === s[0]; var step = button(s[1], 'step' + (current ? ' active' : ''), function () { showStep(id, s[0], s[2]); }, s[0] === 'done' && !passed); step.setAttribute('data-step', s[0]); if (current) step.setAttribute('aria-current', 'step'); stepper.append(step); }); wrap.append(stepper);
    var learn = el('section', { class: 'learn-card', id:'learn-card' }); learn.append(el('h2', { text: 'Learn the idea' })); var explain = el('ul', { class: 'explanation' }); (lesson.explanation || []).forEach(function (line) { explain.append(el('li', { text: line })); }); learn.append(explain); if (lesson.example) learn.append(el('pre', { class: 'lesson-example', text: lesson.example })); learn.append(el('div', { class: 'task' }, [el('strong', { text: 'Your task: ' }), document.createTextNode(lesson.task || 'Complete the workflow.') ])); wrap.append(learn);
    var editorCard = el('section', { class: 'editor-card', id:'editor-card' }); var area = el('textarea', { class: 'editor', id: 'yaml-editor', 'aria-label': 'YAML for ' + lesson.title, spellcheck: 'false' }); area.value = draft; editorCard.append(el('h2', { text: 'Write the YAML' })); if (lesson.instructions && lesson.instructions.length) { var instructions = el('ol', { class:'instructions', 'aria-label':'What to change' }); lesson.instructions.forEach(function (instruction) { var item = el('li'); item.append(inlineText(instruction)); instructions.append(item); }); editorCard.append(el('h3', { class:'instructions-title', text:'What to change' }), instructions); } editorCard.append(el('label', { class: 'file-label', for: 'yaml-editor', text: lesson.file || 'workflow.yml' }), area);
    function onDraft() { state.drafts[id] = area.value; delete state.passes[id]; if (state.completed[id]) delete state.completed[id]; setPhase(id, 'write'); var doneBtn = document.getElementById('mark-done'); if (doneBtn) { doneBtn.disabled = true; doneBtn.textContent = 'Mark as done'; } var old = document.getElementById('check-feedback'); if (old) old.remove(); refreshCompletionUI(id); }
    area.addEventListener('input', onDraft); area.addEventListener('keydown', function(e) { if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') { e.preventDefault(); runTest(); } });
    function runTest() { var source = area.value; var result; try { result = course.check(lesson.id, source); } catch (_) { result = { passed:false, errors:['This draft could not be checked. Review the YAML and try again.'] }; } state.drafts[id] = source; state.passes[id] = { source: source, passed: !!result.passed }; setPhase(id, 'test'); var old = document.getElementById('check-feedback'); if (old) old.remove(); var box = feedback(result); box.id = 'check-feedback'; editorCard.after(box); if (lesson.doneWhen) box.append(el('p', { class:'done-when' }, [el('strong', { text:'You are done when: ' }), document.createTextNode(lesson.doneWhen)])); var doneBtn = document.getElementById('mark-done'); if (doneBtn) doneBtn.disabled = !result.passed; }
    editorCard.append(el('div', { class: 'editor-tools' }, [button('Test this YAML', 'test-button', runTest), el('p', { class: 'check-note', text: 'Checks your YAML; nothing is run on GitHub.' })])); wrap.append(editorCard);
    var extras = el('div', { class: 'hint-solution' }); var hint = el('details'); hint.append(el('summary', { text: 'Need a hint?' }), el('p', { text: lesson.hint || 'Re-read the task and check the key names.' })); var solution = el('details'); solution.append(el('summary', { text: 'View a separate solution' }), el('pre', { class: 'solution-code', text: lesson.solution || '' })); extras.append(hint, solution); wrap.append(extras); if (lesson.source && lesson.source.url) wrap.append(el('p', { class:'source-link' }, [document.createTextNode('Official reference: '), el('a', { href:lesson.source.url, text:lesson.source.label || 'Open guidance', target:'_blank', rel:'noreferrer' })]));
    var doneRow = el('div', { class: 'done-row' }); var mark = button(state.completed[id] ? 'Mark current draft as done' : 'Mark as done', 'done-button', function () { state.completed[id] = true; setPhase(id, 'done'); save(); render(); focusLessonHeading(); }, !passed); mark.id = 'mark-done'; doneRow.append(el('p', { class: 'done-help', text: state.completed[id] ? 'This lesson is in your history. Re-test the current draft before confirming it again.' : 'Pass the current draft to mark this lesson done.' }), mark); wrap.append(doneRow);
    if (state.completed[id]) { var next = lessons()[lessons().indexOf(lesson) + 1]; if (next) wrap.append(el('div', { class: 'continue', id:'lesson-continue' }, [button('Continue to lesson ' + orderedId(next), 'continue-button', function () { select(orderedId(next)); focusLessonHeading(); })])); else wrap.append(el('div', { class: 'continue', id:'lesson-continue' }, [button('See your completion summary', 'continue-button', function () { state.selected = 'complete'; save(); render(); focusLessonHeading(); })])); }
    var reset = button('Reset this exercise', 'reset', function () {
      if (window.confirm('Reset this exercise to its starter YAML?')) {
        delete state.drafts[id]; delete state.passes[id]; delete state.completed[id]; delete state.phases[id]; save(); render();
      }
    });
    wrap.append(el('p', {}, [reset])); return wrap; }
  function complete() { var allDone = doneCount() === lessons().length; var section = el('section', { class: 'complete' }); section.append(el('p', { class:'eyebrow', text: allDone ? 'Learning path complete' : 'Your saved progress' }), el('h1', { text: allDone ? 'You have completed all 17 lessons.' : 'Keep building your workflow skills.' }), el('p', { class:'lede', text: allDone ? 'You have practised the building blocks of dependable GitHub Actions workflows. Revisit any lesson from the path whenever you want a refresh.' : 'Pick up from the learning path whenever you are ready.' }), el('div', { class:'completion-card' }, [el('strong', { text: doneCount() + ' of ' + lessons().length + ' lessons marked complete' }), el('p', { text:'Your drafts and progress stay on this device.' }), button(allDone ? 'Review lesson 01' : 'Continue learning', 'primary', function(){ select(allDone ? '01' : orderedId(lessons().filter(function (lesson) { return !state.completed[orderedId(lesson)]; })[0])); })])); return section; }
  function filteredQuestions() { return questions().filter(function (question) { return (!state.practiceFilter || question.domain === state.practiceFilter) && (!state.reviewWrong || state.reviewQueue.indexOf(question.id) !== -1); }); }
  function practiceView() { var all = questions(); var filtered = filteredQuestions(); var section = el('section', { class:'practice-view' }); section.append(el('p', { class:'eyebrow', text:'Knowledge check' }), el('h1', { text:'Practice questions' }), el('p', { class:'lede', text:'Use these after a lesson to explain your choice and find the supporting official guidance. This records practice in this browser; it is not an exam score or a guarantee of exam readiness.' })); if (!all.length) { section.append(el('div', { class:'empty-state' }, [el('h2', { text:'Questions are being bundled' }), el('p', { text:'The offline course bundle does not include the question bank yet. Rebuild or replace the course runtime, then reopen this page.' })])); return section; }
    var domains = []; all.forEach(function (question) { if (domains.indexOf(question.domain) === -1) domains.push(question.domain); }); var tools = el('div', { class:'practice-tools' }); var label = el('label', { text:'Filter by domain' }); var selectDomain = el('select', { id:'question-domain', 'aria-label':'Filter questions by domain' }); selectDomain.append(el('option', { value:'', text:'All domains' })); domains.forEach(function (domain) { selectDomain.append(el('option', { value:domain, text:domain, selected:state.practiceFilter === domain ? 'selected' : null })); }); selectDomain.addEventListener('change', function () { state.practiceFilter = selectDomain.value; state.practiceIndex = 0; save(); render(); }); label.append(selectDomain); var review = el('label', { class:'review-toggle' }); var check = el('input', { type:'checkbox', checked:state.reviewWrong ? 'checked' : null }); check.addEventListener('change', function () { state.reviewWrong = check.checked; state.reviewQueue = check.checked ? all.filter(function (question) { var answer = state.practice[question.id]; return answer && answer.checked && answer.choice !== question.correct; }).map(function (question) { return question.id; }) : []; state.practiceIndex = 0; save(); render(); }); review.append(check, document.createTextNode(' Review incorrect checked answers')); tools.append(label, review); var attempted = all.filter(function (question) { return state.practice[question.id] && state.practice[question.id].checked; }); var correct = attempted.filter(function (question) { return state.practice[question.id].choice === question.correct; }); tools.append(el('p', { class:'practice-count', text:correct.length + ' correct of ' + attempted.length + ' checked · ' + all.length + ' available' })); section.append(tools);
    if (!filtered.length) { section.append(el('div', { class:'empty-state' }, [el('h2', { text:'No matching questions' }), el('p', { text:'Change the filter or check more questions before reviewing incorrect answers.' })])); return section; }
    state.practiceIndex = Math.min(state.practiceIndex, filtered.length - 1); var question = filtered[state.practiceIndex]; var answer = state.practice[question.id] || {}; var card = el('article', { class:'question-card', 'data-question-id':question.id }); card.append(el('p', { class:'question-position', text:'Question ' + (state.practiceIndex + 1) + ' of ' + filtered.length }), el('p', { class:'question-objective', text:question.objective || question.domain || 'GH-200 objective' }), el('h2', { text:question.question })); var answers = el('fieldset', { class:'answer-list' }); answers.append(el('legend', { text:'Choose one answer' })); question.options.forEach(function (option, index) { var optionLabel = el('label', { class:'answer-option' + (answer.choice === index ? ' selected' : '') }); var radio = el('input', { type:'radio', name:'practice-answer', value:String(index), checked:answer.choice === index ? 'checked' : null, disabled:answer.checked ? 'disabled' : null }); radio.addEventListener('change', function () { state.practice[question.id] = { choice:index, checked:false }; save(); render(); window.setTimeout(function () { var selected = document.querySelector('input[name="practice-answer"][value="' + index + '"]'); if (selected) selected.focus(); }, 0); }); optionLabel.append(radio, el('span', { text:option })); answers.append(optionLabel); }); card.append(answers); var actionRow = el('div', { class:'question-actions' }); actionRow.append(button(answer.checked ? 'Checked' : 'Check answer', 'test-button', function () { if (typeof answer.choice !== 'number') return; state.practice[question.id] = { choice:answer.choice, checked:true }; save(); render(); }, typeof answer.choice !== 'number' || answer.checked)); if (answer.checked) actionRow.append(button('Try again', 'secondary', function () { state.practice[question.id] = { choice:answer.choice, checked:false }; save(); render(); })); card.append(actionRow);
    if (answer.checked) { var right = answer.choice === question.correct; var feedbackBox = el('section', { class:'question-feedback ' + (right ? '' : 'error'), role:'status' }); feedbackBox.append(el('strong', { text:right ? 'Correct.' : 'Not quite.' }), el('p', { text:question.explanation || 'Review the linked guidance, then try again.' })); var sources = Array.isArray(question.sources) ? question.sources : []; if (sources.length) { var sourceList = el('ul', { class:'question-sources' }); sources.forEach(function (source, index) { var url = typeof source === 'string' ? source : source && source.url; var labelText = typeof source === 'string' ? 'Official source ' + (index + 1) : (source && (source.label || source.title)) || 'Official source ' + (index + 1); if (typeof url === 'string' && /^https:\/\//.test(url)) sourceList.append(el('li', {}, [el('a', { href:url, target:'_blank', rel:'noreferrer', text:labelText + ' ↗' })])); }); feedbackBox.append(el('h3', { text:'Read the official source' }), sourceList); } card.append(feedbackBox); }
    var pager = el('div', { class:'question-pager' }); pager.append(button('Previous', 'secondary', function () { state.practiceIndex--; save(); render(); }, state.practiceIndex === 0), button('Next', 'primary', function () { if (state.reviewWrong && answer.checked && answer.choice === question.correct) { state.reviewQueue = state.reviewQueue.filter(function (id) { return id !== question.id; }); } else state.practiceIndex++; save(); render(); }, state.practiceIndex >= filtered.length - 1 && !(state.reviewWrong && answer.checked && answer.choice === question.correct))); card.append(pager); section.append(card, el('p', { class:'exam-library-link' }, [document.createTextNode('Looking for an official practice assessment or sandbox? '), button('Open exam practice resources', 'link-button', function () { changeView('references', 'exam-practice'); })])); return section; }
  function markdownDownload(name, content) { var blob = new Blob([content], { type:'text/markdown;charset=utf-8' }); var url = URL.createObjectURL(blob); var anchor = el('a', { href:url, download:name }); document.body.append(anchor); anchor.click(); anchor.remove(); window.setTimeout(function () { URL.revokeObjectURL(url); }, 0); }
  function referenceDownload(reference) { var header = '# ' + (reference.title || reference.id) + '\n\n'; var meta = 'Source: ' + (reference.url || 'offline note') + '\nKind: ' + (reference.kind || 'reference') + '\nContent: ' + (reference.contentType || 'original-summary') + '\nLicense: ' + (reference.license || 'Not supplied') + '\nRetrieved: ' + (reference.retrievedAt || 'Not supplied') + '\nSource version: ' + (reference.sourceVersion || 'Not supplied') + '\n'; return header + meta + '\n' + (reference.content || reference.summary || 'Offline notes were not included for this source.') + '\n'; }
  function referencesView() { var section = el('section', { class:'references-view' }); section.append(el('p', { class:'eyebrow', text:'Study library' }), el('h1', { text:'References' }), el('p', { class:'lede', text:'Use the learning path to build a workflow, practice questions to test your reasoning, and this library to verify details. Primary sources are official GitHub or Microsoft guidance; secondary sources are clearly labeled context, not an authority.' })); var refs = references(); function renderReferences(group, block) { if (!group.length) block.append(el('p', { class:'empty-copy', text:'No resources in this offline bundle yet.' })); group.forEach(function (reference) { var card = el('article', { class:'reference-card' }); card.append(el('h3', { text:reference.title || reference.id }), el('p', { text:reference.summary || '' })); var metaText = []; if (reference.access) metaText.push(reference.access === 'paid' ? 'Freemium/paid access may apply' : 'Free access'); metaText.push(reference.contentType === 'source-snapshot' ? 'Archived source snapshot' : 'Original summary/notes'); if (reference.license) metaText.push('License: ' + reference.license); if (reference.retrievedAt) metaText.push('Retrieved: ' + reference.retrievedAt); if (reference.sourceVersion) metaText.push('Source version: ' + reference.sourceVersion); card.append(el('p', { class:'reference-meta', text:metaText.join(' · ') })); var links = el('div', { class:'reference-links' }); if (typeof reference.url === 'string' && /^https:\/\//.test(reference.url)) links.append(el('a', { href:reference.url, target:'_blank', rel:'noreferrer', text:'Open current online source ↗' })); if (reference.content) { var offline = el('details', { class:'offline-read' }); offline.append(el('summary', { text:'Read offline' }), el('pre', { text:reference.content })); links.append(offline); } links.append(button(reference.contentType === 'source-snapshot' ? 'Download source snapshot' : 'Download study notes', 'secondary', function () { markdownDownload((reference.id || 'reference') + '.md', referenceDownload(reference)); })); card.append(links); block.append(card); }); }
    var exams = refs.filter(function (reference) { return reference.category === 'exam-practice'; }); var examBlock = el('section', { class:'reference-group exam-practice', id:'exam-practice' }); examBlock.append(el('h2', { text:'Exam practice resources' }), el('p', { text:'These are practice resources, not released past exam papers. No official past GH-200 papers are verified. Use the official assessment to find gaps; the sandbox is an interface familiarization resource.' })); renderReferences(exams, examBlock); section.append(examBlock); ['primary','secondary'].forEach(function (kind) { var group = refs.filter(function (reference) { return reference.kind === kind && reference.category !== 'exam-practice'; }); var block = el('section', { class:'reference-group' }); block.append(el('h2', { text:kind === 'primary' ? 'Primary sources' : 'Secondary sources' }), el('p', { text:kind === 'primary' ? 'Official, current online documentation. Offline snapshots are archived study copies and may age; use the source link for current guidance.' : 'Supplementary explanation or study context. Check primary guidance before acting.' })); renderReferences(group, block); section.append(block); }); [['cheatSheet','Download cheat sheet'],['coverage','Download coverage map']].forEach(function (item) { var documentData = course && course[item[0]]; if (documentData && typeof documentData.content === 'string') section.append(el('section', { class:'download-card' }, [el('h2', { text:documentData.title || item[1] }), el('p', { text:'A bundled offline study aid.' }), button(item[1], 'secondary', function () { markdownDownload(item[0] + '.md', '# ' + (documentData.title || item[1]) + '\n\n' + documentData.content); })])); }); return section; }
  function render() { root.replaceChildren(); if (!course || !Array.isArray(course.lessons) || typeof course.check !== 'function') { root.append(el('main', { class:'error-state', id:'main' }, [el('h1', { text:'Course content is not ready yet.' }), el('p', { text:'Please keep this folder together and open index.html again.' })])); return; } if (!find(state.selected) && state.selected !== 'complete' && state.selected !== '') state.selected = ''; if (state.selected === 'complete' && doneCount() !== lessons().length) state.selected = ''; var main = el('main', { id:'main', tabindex:'-1' }); if (state.view === 'practice') main.append(practiceView()); else if (state.view === 'references') main.append(referencesView()); else main.append(state.selected === 'complete' ? complete() : (!state.selected ? intro() : lessonView(find(state.selected)))); root.append(header(), state.view === 'learning' ? el('div', { class:'shell' }, [sidebar(), main]) : el('div', { class:'content-shell' }, [main])); }
  function labelReferenceDownloads() { Array.prototype.forEach.call(document.querySelectorAll('.reference-card button'), function (download) { var title = download.closest('.reference-card').querySelector('h3'); if (title && /^Download /.test(download.textContent)) download.setAttribute('aria-label', download.textContent + ': ' + title.textContent); }); }
  load(); render(); labelReferenceDownloads(); new MutationObserver(labelReferenceDownloads).observe(root, { childList:true, subtree:true });
}());
