(function () {
  'use strict';
  var root = document.getElementById('app');
  var course = window.GH200Course;
  var STORE_KEY = 'actions-academy-gh200-v1';
  var state = { view: 'learning', selected: '', stage: '', drafts: {}, completed: {}, phases: {}, passes: {}, practice: {}, practiceFilter: '', reviewWrong: false, reviewQueue: [], practiceIndex: 0, referenceSection: '' };

  function el(tag, attrs, children) {
    var node = document.createElement(tag); var key;
    attrs = attrs || {}; children = children == null ? [] : (Array.isArray(children) ? children : [children]);
    for (key in attrs) { if (attrs[key] == null || attrs[key] === false) continue; if (key === 'class') node.className = attrs[key]; else if (key === 'text') node.textContent = attrs[key]; else if (key.indexOf('on') === 0) node.addEventListener(key.slice(2), attrs[key]); else node.setAttribute(key, attrs[key]); }
    children.forEach(function (child) { node.append(child && child.nodeType ? child : document.createTextNode(String(child))); }); return node;
  }
  function questions() { return Array.isArray(course && course.questions) ? course.questions.filter(function (question) { return question && typeof question.id === 'string' && Array.isArray(question.options) && typeof question.correct === 'number' && question.correct >= 0 && question.correct < question.options.length; }) : []; }
  function displayDomain(domain) { var labels = { 'author-manage':'Author and manage workflows', 'consume-troubleshoot':'Consume and troubleshoot workflows', 'author-actions':'Author and maintain actions', 'enterprise':'Manage GitHub Actions for the enterprise', 'secure-optimize':'Secure and optimize automation' }; return labels[domain] || String(domain || '').split(/[-_]+/).map(function (word) { return word.charAt(0).toUpperCase() + word.slice(1); }).join(' '); }
  function displayObjective(objective) { var labels = { 'triggers-inputs':'Workflow triggers and inputs', 'reusable-inputs':'Reusable workflow inputs', 'job-outputs':'Job outputs', 'permissions-events':'Permissions and events', 'reusable-vs-composite':'Reusable workflows and composite actions', 'permissions-token':'Permissions and tokens' }; return labels[objective] || String(objective || '').split(/[-_]+/).map(function (word) { return word.charAt(0).toUpperCase() + word.slice(1); }).join(' '); }
  function references() { return Array.isArray(course && course.references) ? course.references.filter(function (reference) { return reference && typeof reference.id === 'string'; }) : []; }
  function load() { try { var parsed = JSON.parse(localStorage.getItem(STORE_KEY)); var known = lessons().map(orderedId); var knownQuestions = questions().map(function (question) { return question.id; }); if (!parsed || typeof parsed !== 'object') return; state.view = ['learning','practice','references'].indexOf(parsed.view) !== -1 ? parsed.view : 'learning'; state.selected = typeof parsed.selected === 'string' && (parsed.selected === '' || parsed.selected === 'complete' || known.indexOf(parsed.selected) !== -1) ? parsed.selected : ''; state.stage = typeof parsed.stage === 'string' && stages().map(function (group) { return group.stage; }).indexOf(parsed.stage) !== -1 ? parsed.stage : ''; if (parsed.drafts && typeof parsed.drafts === 'object') Object.keys(parsed.drafts).forEach(function (id) { if (known.indexOf(id) !== -1 && typeof parsed.drafts[id] === 'string') state.drafts[id] = parsed.drafts[id]; }); if (parsed.completed && typeof parsed.completed === 'object') Object.keys(parsed.completed).forEach(function (id) { if (known.indexOf(id) !== -1 && parsed.completed[id] === true) state.completed[id] = true; }); if (parsed.phases && typeof parsed.phases === 'object') Object.keys(parsed.phases).forEach(function (id) { if (known.indexOf(id) !== -1 && ['learn','write','test','done'].indexOf(parsed.phases[id]) !== -1) state.phases[id] = parsed.phases[id]; }); if (parsed.practice && typeof parsed.practice === 'object') Object.keys(parsed.practice).forEach(function (id) { var answer = parsed.practice[id]; if (knownQuestions.indexOf(id) !== -1 && answer && typeof answer === 'object' && Number.isInteger(answer.choice) && answer.choice >= 0 && answer.choice < questions().filter(function (question) { return question.id === id; })[0].options.length && typeof answer.checked === 'boolean') state.practice[id] = { choice: answer.choice, checked: answer.checked }; }); if (typeof parsed.practiceFilter === 'string') state.practiceFilter = parsed.practiceFilter; state.reviewWrong = parsed.reviewWrong === true; if (Array.isArray(parsed.reviewQueue)) state.reviewQueue = parsed.reviewQueue.filter(function (id, index, list) { return knownQuestions.indexOf(id) !== -1 && list.indexOf(id) === index; }); if (Number.isInteger(parsed.practiceIndex) && parsed.practiceIndex >= 0) state.practiceIndex = parsed.practiceIndex; } catch (_) {} }
  function save() { try { localStorage.setItem(STORE_KEY, JSON.stringify({ view: state.view, selected: state.selected, stage: state.stage, drafts: state.drafts, completed: state.completed, phases: state.phases, practice: state.practice, practiceFilter: state.practiceFilter, reviewWrong: state.reviewWrong, reviewQueue: state.reviewQueue, practiceIndex: state.practiceIndex })); } catch (_) {} }
  function lessons() { return course.lessons || []; }
  function stages() { var groups = []; lessons().forEach(function (lesson) { var group = groups.filter(function (item) { return item.stage === lesson.stage; })[0]; if (!group) { group = { stage: lesson.stage, lessons: [] }; groups.push(group); } group.lessons.push(lesson); }); return groups; }
  function find(id) { return lessons().filter(function (lesson) { return orderedId(lesson) === id; })[0]; }
  function orderedId(lesson) { return String(lesson.index || lesson.id).padStart(2, '0').slice(0, 2); }
  function select(id) { state.selected = id; state.stage = find(id).stage; state.passes = {}; save(); render(); window.scrollTo(0, 0); }
  function selectStage(name) { state.stage = name; state.selected = ''; save(); render(); window.scrollTo(0, 0); }
  function backToRoadmap() { state.selected = ''; state.stage = ''; save(); render(); window.scrollTo(0, 0); }
  function doneCount() { return Object.keys(state.completed).length; }
  function focusLessonHeading() { var heading = document.querySelector('#main h1'); if (heading) { heading.tabIndex = -1; heading.focus({ preventScroll: true }); } }
  function refreshCompletionUI(id) {
    var tag = document.getElementById('lesson-status'); var step = document.getElementById('step-done'); var item = document.querySelector('[data-lesson-item="' + id + '"]'); var dot = document.querySelector('[data-lesson-dot="' + id + '"]'); var continueArea = document.getElementById('lesson-continue');
    if (tag) tag.textContent = state.completed[id] ? 'Completed' : 'Practice now';
    if (step) step.classList.toggle('ready', !!state.completed[id]);
    if (item) item.classList.toggle('done', !!state.completed[id]);
    if (dot) dot.textContent = state.completed[id] ? '✓' : id;
    var mapNode = document.querySelector('[data-map-lesson="' + id + '"]'); var mapState = document.querySelector('[data-map-state="' + id + '"]');
    if (mapNode) mapNode.classList.toggle('done', !!state.completed[id]);
    if (mapState) mapState.textContent = state.completed[id] ? 'Done' : 'Open lesson';
    if (!state.completed[id] && continueArea) continueArea.remove();
  }
  function setPhase(id, phase) { state.phases[id] = phase; save(); }
  function inlineText(text) { var fragment = document.createDocumentFragment(); String(text || '').split(/(`[^`]+`)/g).forEach(function (part) { if (part.charAt(0) === '`' && part.charAt(part.length - 1) === '`') fragment.append(el('code', { text:part.slice(1, -1) })); else fragment.append(document.createTextNode(part)); }); return fragment; }
  function button(text, className, handler, disabled, ariaLabel) { return el('button', { class: className, type: 'button', onclick: handler, disabled: disabled ? 'disabled' : null, 'aria-label': ariaLabel || null, text: text }); }
  function changeView(view, referenceSection) { state.view = view; state.referenceSection = referenceSection || ''; if (view !== 'learning') { state.selected = ''; state.stage = ''; } save(); render(); window.scrollTo(0, 0); focusLessonHeading(); }
  function header() { var nav = el('nav', { class:'top-nav', 'aria-label':'Course sections' }); [['learning','Learning path'],['practice','Practice questions'],['references','References']].forEach(function (item) { var link = button(item[1], 'top-nav-link', function () { changeView(item[0]); }); if (state.view === item[0]) link.setAttribute('aria-current', 'page'); nav.append(link); }); return el('header', { class: 'topbar' }, [el('a', { class: 'brand', href: '#', text: 'GH-200 practice', onclick: function (e) { e.preventDefault(); state.view = 'learning'; backToRoadmap(); focusLessonHeading(); } }), nav]); }
  function intro() { var section = el('section', { class: 'intro' }); var groups = stages(); section.append(el('h1', { text: 'Your GitHub Actions learning path' }), el('p', { class: 'lede', text: 'Choose a topic, then a lesson. Write YAML, test it, and save your progress.' }));
    var path = el('div', { class: 'path roadmap', id: 'path', 'aria-label':'Four topic learning roadmap' }); path.append(el('div', { class:'diagram-root', text:'GH-200' }), el('div', { class:'roadmap-connector', 'aria-hidden':'true' })); groups.forEach(function (group, index) { var done = group.lessons.filter(function (lesson) { return state.completed[orderedId(lesson)]; }).length; var complete = done === group.lessons.length; var stage = el('section', { class:'flow-stage' }); stage.append(el('button', { class: 'stage-card' + (complete ? ' done-stage' : ''), type: 'button', onclick: function(){ selectStage(group.stage); focusLessonHeading(); }, 'aria-label':group.stage + ', ' + done + ' of ' + group.lessons.length + ' lessons complete' }, [el('b', { text: group.stage }), el('span', { text: complete ? '✓ Complete' : done + '/' + group.lessons.length + ' complete' })])); path.append(stage); if (index < groups.length - 1) path.append(el('div', { class:'roadmap-connector', 'aria-hidden':'true' })); }); section.append(path); return section; }
  function stageView(group) { var section = el('section', { class:'stage-view' }); var nodes = el('div', { class:'lesson-flow', 'aria-label': group.stage + ' lesson sequence' }); var nextIndex = group.lessons.findIndex(function (lesson) { return !state.completed[orderedId(lesson)]; }); section.append(button('← Back to roadmap', 'back-button', function () { backToRoadmap(); focusLessonHeading(); }), el('p', { class:'eyebrow', text:'Topic lesson map' }), el('h1', { text:group.stage }), el('p', { class:'lede', text:'Follow the line from top to bottom. Start with the highlighted lesson.' }), el('div', { class:'topic-root', text:group.stage })); group.lessons.forEach(function (lesson, index) { var id = orderedId(lesson); var done = !!state.completed[id]; var isNext = index === nextIndex; var stateText = done ? '✓ Completed' : (isNext ? (index === 0 ? 'Start here' : 'Up next') : ''); var children = [el('b', { text:lesson.title })]; if (stateText) children.push(el('small', { class:'lesson-map-state' + (isNext ? ' next-state' : ''), 'data-map-state':id, text:stateText })); var node = el('button', { class:'lesson-bubble' + (done ? ' done' : '') + (isNext ? ' next' : ''), type:'button', 'data-map-lesson':id, 'aria-label':lesson.title + (done ? ', completed' : (isNext ? ', ' + stateText.toLowerCase() : '')), onclick:function(){ select(id); focusLessonHeading(); } }, children); nodes.append(node); if (index < group.lessons.length - 1) nodes.append(el('div', { class:'lesson-connector', 'aria-hidden':'true' })); }); section.append(nodes); return section; }
  function feedback(result) { var box = el('section', { class: 'feedback ' + (result.passed ? '' : 'error'), role: 'status' }); box.append(el('p', { text: result.passed ? 'Looks good — this draft meets the exercise checks.' : 'Not quite yet — adjust the YAML and try again.' })); if (!result.passed && result.errors && result.errors.length) { var ul = el('ul'); result.errors.forEach(function (message) { ul.append(el('li', { text: message })); }); box.append(ul); } return box; }
  function lessonView(lesson) { var id = orderedId(lesson); var draft = Object.prototype.hasOwnProperty.call(state.drafts, id) ? state.drafts[id] : (lesson.starter || ''); var passed = state.passes[id] && state.passes[id].source === draft && state.passes[id].passed; var wrap = el('article');
    wrap.append(el('header', { class: 'lesson-head' }, [el('p', { class: 'eyebrow', text: 'Lesson ' + id + ' · ' + lesson.stage }), el('h1', { text: lesson.title }), el('p', { text: lesson.summary || '' }), el('span', { class: 'tag', id:'lesson-status', text: state.completed[id] ? 'Completed' : 'Practice now' })]));
    wrap.append(button('← Back to ' + lesson.stage, 'back-button', function () { state.selected = ''; state.stage = lesson.stage; save(); render(); window.scrollTo(0, 0); focusLessonHeading(); }));
    var learn = el('section', { class: 'learn-card', id:'learn-card' }); learn.append(el('h2', { text: 'Learn the idea' })); var explain = el('ul', { class: 'explanation' }); (lesson.explanation || []).forEach(function (line) { explain.append(el('li', { text: line })); }); learn.append(explain); if (lesson.example) learn.append(el('pre', { class: 'lesson-example', text: lesson.example })); learn.append(el('div', { class: 'task' }, [el('strong', { text: 'Your task: ' }), document.createTextNode(lesson.task || 'Complete the workflow.') ])); wrap.append(learn);
    var editorCard = el('section', { class: 'editor-card', id:'editor-card' }); var area = el('textarea', { class: 'editor', id: 'yaml-editor', 'aria-label': 'YAML for ' + lesson.title, spellcheck: 'false' }); area.value = draft; editorCard.append(el('h2', { text: 'Write the YAML' })); if (lesson.instructions && lesson.instructions.length) { var instructions = el('ol', { class:'instructions', 'aria-label':'What to change' }); lesson.instructions.forEach(function (instruction) { var item = el('li'); item.append(inlineText(instruction)); instructions.append(item); }); editorCard.append(el('h3', { class:'instructions-title', text:'What to change' }), instructions); } editorCard.append(el('label', { class: 'file-label', for: 'yaml-editor', text: lesson.file || 'workflow.yml' }), area);
    function onDraft() { var wasCompleted = !!state.completed[id]; state.drafts[id] = area.value; delete state.passes[id]; if (wasCompleted) delete state.completed[id]; setPhase(id, 'write'); var doneBtn = document.getElementById('mark-done'); if (doneBtn) { doneBtn.disabled = true; doneBtn.textContent = 'Mark as done'; } if (wasCompleted) { var doneRow = document.getElementById('done-row'); if (doneRow) { doneRow.replaceChildren(el('p', { class: 'done-help', text: 'Pass the current draft to mark this lesson done.' }), (function () { var nextMark = button('Mark as done', 'done-button', function () { state.completed[id] = true; setPhase(id, 'done'); save(); render(); focusLessonHeading(); }, true); nextMark.id = 'mark-done'; return nextMark; })()); } } var old = document.getElementById('check-feedback'); if (old) old.remove(); refreshCompletionUI(id); }
    area.addEventListener('input', onDraft); area.addEventListener('keydown', function(e) { if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') { e.preventDefault(); runTest(); } });
    function runTest() { var source = area.value; var result; try { result = course.check(lesson.id, source); } catch (_) { result = { passed:false, errors:['This draft could not be checked. Review the YAML and try again.'] }; } state.drafts[id] = source; state.passes[id] = { source: source, passed: !!result.passed }; setPhase(id, 'test'); var old = document.getElementById('check-feedback'); if (old) old.remove(); var box = feedback(result); box.id = 'check-feedback'; editorCard.after(box); if (lesson.doneWhen) box.append(el('p', { class:'done-when' }, [el('strong', { text:'You are done when: ' }), document.createTextNode(lesson.doneWhen)])); var doneBtn = document.getElementById('mark-done'); if (doneBtn) doneBtn.disabled = !result.passed; }
    editorCard.append(el('div', { class: 'editor-tools' }, [button('Test this YAML', 'test-button', runTest), el('p', { class: 'check-note', text: 'Checks your YAML; nothing is run on GitHub.' })])); wrap.append(editorCard);
    var extras = el('div', { class: 'hint-solution' }); var hint = el('details'); hint.append(el('summary', { text: 'Need a hint?' }), el('p', { text: lesson.hint || 'Re-read the task and check the key names.' })); var solution = el('details'); solution.append(el('summary', { text: 'View a separate solution' }), el('pre', { class: 'solution-code', text: lesson.solution || '' })); extras.append(hint, solution); wrap.append(extras); if (lesson.source && lesson.source.url) wrap.append(el('p', { class:'source-link' }, [document.createTextNode('Official reference: '), el('a', { href:lesson.source.url, text:lesson.source.label || 'Open guidance', target:'_blank', rel:'noreferrer' })]));
    var doneRow = el('div', { class: 'done-row', id:'done-row' }); if (state.completed[id]) { doneRow.append(el('p', { class: 'done-help completed-help', text: 'Completed. Your saved draft is ready whenever you want to review it.' })); } else { var mark = button('Mark as done', 'done-button', function () { state.completed[id] = true; setPhase(id, 'done'); save(); render(); focusLessonHeading(); }, !passed); mark.id = 'mark-done'; doneRow.append(el('p', { class: 'done-help', text: 'Pass the current draft to mark this lesson done.' }), mark); } wrap.append(doneRow);
    if (state.completed[id]) { var next = lessons()[lessons().indexOf(lesson) + 1]; if (next) wrap.append(el('div', { class: 'continue', id:'lesson-continue' }, [button('Continue: ' + next.title, 'continue-button', function () { select(orderedId(next)); focusLessonHeading(); })])); else wrap.append(el('div', { class: 'continue', id:'lesson-continue' }, [button('See your completion summary', 'continue-button', function () { state.selected = 'complete'; save(); render(); focusLessonHeading(); })])); }
    var reset = button('Reset this exercise', 'reset', function () {
      if (window.confirm('Reset this exercise to its starter YAML?')) {
        delete state.drafts[id]; delete state.passes[id]; delete state.completed[id]; delete state.phases[id]; save(); render();
      }
    });
    wrap.append(el('p', {}, [reset])); return wrap; }
  function complete() { var allDone = doneCount() === lessons().length; var section = el('section', { class: 'complete' }); section.append(el('p', { class:'eyebrow', text: allDone ? 'Learning path complete' : 'Your saved progress' }), el('h1', { text: allDone ? 'You have completed all 17 lessons.' : 'Keep building your workflow skills.' }), el('p', { class:'lede', text: allDone ? 'You have practised the building blocks of dependable GitHub Actions workflows. Revisit any lesson from the roadmap whenever you want a refresh.' : 'Pick up from the learning path whenever you are ready.' }), el('div', { class:'completion-card' }, [el('strong', { text: doneCount() + ' of ' + lessons().length + ' lessons marked complete' }), el('p', { text:'Your drafts and progress stay on this device.' }), button('View roadmap', 'primary', backToRoadmap)])); return section; }
  function filteredQuestions() { return questions().filter(function (question) { return (!state.practiceFilter || question.domain === state.practiceFilter) && (!state.reviewWrong || state.reviewQueue.indexOf(question.id) !== -1); }); }
  function practiceView() { var all = questions(); var filtered = filteredQuestions(); var section = el('section', { class:'practice-view' }); section.append(el('p', { class:'eyebrow', text:'Knowledge check' }), el('h1', { text:'Practice questions' }), el('p', { class:'lede', text:'Use these after a lesson to explain your choice and find the supporting official guidance. This records practice in this browser; it is not an exam score or a guarantee of exam readiness.' })); if (!all.length) { section.append(el('div', { class:'empty-state' }, [el('h2', { text:'Questions are being bundled' }), el('p', { text:'The offline course bundle does not include the question bank yet. Rebuild or replace the course runtime, then reopen this page.' })])); return section; }
    var domains = []; all.forEach(function (question) { if (domains.indexOf(question.domain) === -1) domains.push(question.domain); }); var tools = el('div', { class:'practice-tools' }); var label = el('label', { class:'practice-filter', text:'Focus area' }); var selectDomain = el('select', { id:'question-domain', 'aria-label':'Filter questions by focus area' }); selectDomain.append(el('option', { value:'', text:'All focus areas' })); domains.forEach(function (domain) { selectDomain.append(el('option', { value:domain, text:displayDomain(domain), selected:state.practiceFilter === domain ? 'selected' : null })); }); selectDomain.addEventListener('change', function () { state.practiceFilter = selectDomain.value; state.practiceIndex = 0; save(); render(); }); label.append(selectDomain); var review = el('label', { class:'review-toggle' }); var check = el('input', { type:'checkbox', checked:state.reviewWrong ? 'checked' : null }); check.addEventListener('change', function () { state.reviewWrong = check.checked; state.reviewQueue = check.checked ? all.filter(function (question) { var answer = state.practice[question.id]; return answer && answer.checked && answer.choice !== question.correct; }).map(function (question) { return question.id; }) : []; state.practiceIndex = 0; save(); render(); }); review.append(check, document.createTextNode(' Review mistakes')); tools.append(label, review); var attempted = all.filter(function (question) { return state.practice[question.id] && state.practice[question.id].checked; }); var correct = attempted.filter(function (question) { return state.practice[question.id].choice === question.correct; }); tools.append(el('p', { class:'practice-count' }, [el('strong', { text:correct.length + ' correct · ' + attempted.length + ' answered' }), el('span', { text:all.length + ' questions available' })])); section.append(tools);
    if (!filtered.length) { section.append(el('div', { class:'empty-state' }, [el('h2', { text:'No matching questions' }), el('p', { text:'Change the filter or check more questions before reviewing incorrect answers.' })])); return section; }
    state.practiceIndex = Math.min(state.practiceIndex, filtered.length - 1); var question = filtered[state.practiceIndex]; var answer = state.practice[question.id] || {}; var card = el('article', { class:'question-card', 'data-question-id':question.id }); card.append(el('p', { class:'question-position', text:'Question ' + (state.practiceIndex + 1) + ' of ' + filtered.length }), el('p', { class:'question-objective', text:displayObjective(question.objective || question.domain) }), el('h2', { text:question.question })); var answers = el('fieldset', { class:'answer-list' }); answers.append(el('legend', { text:'Choose one answer' })); question.options.forEach(function (option, index) { var optionLabel = el('label', { class:'answer-option' + (answer.choice === index ? ' selected' : '') }); var radio = el('input', { type:'radio', name:'practice-answer', value:String(index), checked:answer.choice === index ? 'checked' : null, disabled:answer.checked ? 'disabled' : null }); radio.addEventListener('change', function () { state.practice[question.id] = { choice:index, checked:false }; save(); render(); window.setTimeout(function () { var selected = document.querySelector('input[name="practice-answer"][value="' + index + '"]'); if (selected) selected.focus(); }, 0); }); optionLabel.append(radio, el('span', { text:option })); answers.append(optionLabel); }); card.append(answers); var actionRow = el('div', { class:'question-actions' }); actionRow.append(button(answer.checked ? 'Checked' : 'Check answer', 'test-button', function () { if (typeof answer.choice !== 'number') return; state.practice[question.id] = { choice:answer.choice, checked:true }; save(); render(); }, typeof answer.choice !== 'number' || answer.checked)); if (answer.checked) actionRow.append(button('Try again', 'secondary', function () { state.practice[question.id] = { choice:answer.choice, checked:false }; save(); render(); })); card.append(actionRow);
    if (answer.checked) { var right = answer.choice === question.correct; var feedbackBox = el('section', { class:'question-feedback ' + (right ? '' : 'error'), role:'status' }); feedbackBox.append(el('strong', { text:right ? 'Correct.' : 'Not quite.' }), el('p', { text:question.explanation || 'Review the linked guidance, then try again.' })); var sources = Array.isArray(question.sources) ? question.sources : []; if (sources.length) { var sourceList = el('ul', { class:'question-sources' }); sources.forEach(function (source, index) { var url = typeof source === 'string' ? source : source && source.url; var labelText = typeof source === 'string' ? 'Official source ' + (index + 1) : (source && (source.label || source.title)) || 'Official source ' + (index + 1); if (typeof url === 'string' && /^https:\/\//.test(url)) sourceList.append(el('li', {}, [el('a', { href:url, target:'_blank', rel:'noreferrer', text:labelText + ' ↗' })])); }); feedbackBox.append(el('h3', { text:'Read the official source' }), sourceList); } card.append(feedbackBox); }
    var pager = el('div', { class:'question-pager' }); pager.append(button('Previous', 'secondary', function () { state.practiceIndex--; save(); render(); }, state.practiceIndex === 0), button('Next', 'primary', function () { if (state.reviewWrong && answer.checked && answer.choice === question.correct) { state.reviewQueue = state.reviewQueue.filter(function (id) { return id !== question.id; }); } else state.practiceIndex++; save(); render(); }, state.practiceIndex >= filtered.length - 1 && !(state.reviewWrong && answer.checked && answer.choice === question.correct))); card.append(pager); section.append(card, el('p', { class:'exam-library-link' }, [document.createTextNode('Looking for an official practice assessment or sandbox? '), button('Open exam practice resources', 'link-button', function () { changeView('references', 'exam-practice'); })])); return section; }
  function markdownDownload(name, content) { var blob = new Blob([content], { type:'text/markdown;charset=utf-8' }); var url = URL.createObjectURL(blob); var anchor = el('a', { href:url, download:name }); document.body.append(anchor); anchor.click(); anchor.remove(); window.setTimeout(function () { URL.revokeObjectURL(url); }, 0); }
  function referenceDownload(reference) { var header = '# ' + (reference.title || reference.id) + '\n\n'; var meta = 'Source: ' + (reference.url || 'offline note') + '\nKind: ' + (reference.kind || 'reference') + '\nContent: ' + (reference.contentType || 'original-summary') + '\nLicense: ' + (reference.license || 'Not supplied') + '\nRetrieved: ' + (reference.retrievedAt || 'Not supplied') + '\nSource version: ' + (reference.sourceVersion || 'Not supplied') + '\n'; return header + meta + '\n' + (reference.content || reference.summary || 'Offline notes were not included for this source.') + '\n'; }
  function render() { root.replaceChildren(); if (!course || !Array.isArray(course.lessons) || typeof course.check !== 'function') { root.append(el('main', { class:'error-state', id:'main' }, [el('h1', { text:'Course content is not ready yet.' }), el('p', { text:'Please keep this folder together and open index.html again.' })])); return; } if (!find(state.selected) && state.selected !== 'complete' && state.selected !== '') state.selected = ''; if (state.selected === 'complete' && doneCount() !== lessons().length) state.selected = ''; if (state.stage && !stages().filter(function (group) { return group.stage === state.stage; }).length) state.stage = ''; var main = el('main', { id:'main', tabindex:'-1' }); if (state.view === 'practice') main.append(practiceView()); else if (state.view === 'references') main.append(referencesView()); else main.append(state.selected === 'complete' ? complete() : (state.selected ? lessonView(find(state.selected)) : (state.stage ? stageView(stages().filter(function (group) { return group.stage === state.stage; })[0]) : intro()))); root.append(header(), el('div', { class:'content-shell' }, [main])); }
  function referencesView() {
    var section = el('section', { class:'references-view' });
    var refs = references();
    section.append(
      el('p', { class:'eyebrow', text:'Study library' }),
      el('h1', { text:'References' }),
      el('p', { class:'lede', text:'Primary sources are official guidance; community and paid resources are labeled.' })
    );
    function badgeFor(reference) {
      return reference.access === 'paid' ? 'Paid' : (reference.kind === 'primary' ? 'Official' : 'Community');
    }
    function renderRow(reference) {
      var name = reference.title || reference.id;
      var badge = badgeFor(reference);
      var card = el('article', { class:'reference-card compact-reference', 'data-reference-id':reference.id });
      var top = el('div', { class:'reference-top' }, [
        el('h3', { text:name }),
        el('span', { class:'reference-badge ' + badge.toLowerCase(), text:badge })
      ]);
      if (typeof reference.url === 'string' && /^https:\/\//.test(reference.url)) {
        top.append(el('a', { class:'reference-open', href:reference.url, target:'_blank', rel:'noreferrer', 'aria-label':'Open ' + name, text:'Open ↗' }));
      }
      card.append(top);
      if (reference.content) {
        var type = reference.contentType === 'source-snapshot' ? 'source-snapshot' : 'original-summary';
        var details = el('details', { class:'reference-details' });
        details.append(
          el('summary', { text:'Details' }),
          el('p', { text:reference.summary || '' }),
          el('p', { class:'reference-meta', text:'Type: ' + type + ' · License: ' + (reference.license || 'Not supplied') + ' · Retrieved: ' + (reference.retrievedAt || 'Not supplied') + ' · Version: ' + (reference.sourceVersion || 'Not supplied') }),
          el('details', { class:'offline-read' }, [el('summary', { text:'Read offline' }), el('pre', { text:reference.content })]),
          button(type === 'source-snapshot' ? 'Download source snapshot' : 'Download study notes', 'secondary', function () { markdownDownload((reference.id || 'reference') + '.md', referenceDownload(reference)); }, false, (type === 'source-snapshot' ? 'Download source snapshot: ' : 'Download study notes: ') + name)
        );
        card.append(details);
      }
      return card;
    }
    function renderGroup(group, title, id, notice) {
      var block = el('section', { class:'reference-group' + (id ? ' exam-practice' : ''), id:id || null });
      block.append(el('h2', { text:title }));
      if (notice) block.append(el('p', { text:notice }));
      if (!group.length) block.append(el('p', { class:'empty-copy', text:'No resources in this offline bundle yet.' }));
      group.forEach(function (reference) { block.append(renderRow(reference)); });
      return block;
    }
    var exams = refs.filter(function (reference) { return reference.category === 'exam-practice'; });
    section.append(
      renderGroup(exams, 'Exam practice resources', 'exam-practice', 'Practice resources, not released past exam papers.'),
      renderGroup(refs.filter(function (reference) { return reference.kind === 'primary' && reference.category !== 'exam-practice'; }), 'Official sources'),
      renderGroup(refs.filter(function (reference) { return reference.kind !== 'primary' && reference.category !== 'exam-practice'; }), 'Community and paid sources')
    );
    [['cheatSheet','Download cheat sheet'],['coverage','Download coverage map']].forEach(function (item) {
      var data = course && course[item[0]];
      if (data && typeof data.content === 'string') section.append(el('section', { class:'download-card' }, [el('h2', { text:data.title || item[1] }), button(item[1], 'secondary', function () { markdownDownload(item[0] + '.md', '# ' + (data.title || item[1]) + '\n\n' + data.content); })]));
    });
    return section;
  }
  function labelReferenceDownloads() { Array.prototype.forEach.call(document.querySelectorAll('.reference-card button'), function (download) { var title = download.closest('.reference-card').querySelector('h3'); if (title && /^Download /.test(download.textContent)) download.setAttribute('aria-label', download.textContent + ': ' + title.textContent); }); }
  load(); render(); labelReferenceDownloads(); new MutationObserver(labelReferenceDownloads).observe(root, { childList:true, subtree:true });
}());
